using System.Text.Json.Serialization;

namespace CoreLayer.Citrix.Adc.NitroData.Api.Statistics.Dns
{
    public class DnsStats
    {
        [JsonPropertyName("dnstotqueries")]public string DnsTotalQueries { get; set; }
        [JsonPropertyName("dnsqueriesrate")]public double? DnsQueriesRate { get; set; }
        [JsonPropertyName("dnstotmultiquery")]public string DnsTotalMultiQuery { get; set; }
        [JsonPropertyName("dnstotanswers")]public string DnsTotalAnswers { get; set; }
        [JsonPropertyName("dnsanswersrate")]public double? DnsAnswersRate { get; set; } 
        [JsonPropertyName("dnstotserverresponse")]public string DnsTotalServerResponse { get; set; }
        [JsonPropertyName("dnsserverresponserate")]public double? DnsServerResponseRate { get; set; }
        [JsonPropertyName("dnstotrecupdate")]public string DnsTotalRecordUpdate { get; set; }
        [JsonPropertyName("dnscurcachesize")]public string DnsCurrentCacheSize { get; set; }
        [JsonPropertyName("dnscurnegcachesize")]public string DnsCurrentNegativeCacheSize { get; set; }
        [JsonPropertyName("dnstotjumboqueries")]public string DnsTotalJumboQueries { get; set; }
        [JsonPropertyName("dnsjumboqueriesrate")]public double? DnsJumboQueriesRate { get; set; }
        [JsonPropertyName("dnstotjumboanswers")]public string DnsTotalJumboAnswers { get; set; }
        [JsonPropertyName("dnsjumboanswersrate")]public double? DnsJumboAnswersRate { get; set; }
        [JsonPropertyName("dnstotjumboserverresponses")]public string DnsTotalJumboServerResponses { get; set; }
        [JsonPropertyName("dnsjumboserverresponsesrate")]public double? DnsJumboServerResponsesRate { get; set; }
        [JsonPropertyName("dnstotauthans")]public string DnsTotalAuthoritativeAnswers { get; set; }
        [JsonPropertyName("dnstotserverquery")]public string DnsTotalServerQuery { get; set; }
        [JsonPropertyName("dnsserverqueryrate")]public double? DnsServerQueryRate { get; set; }
        [JsonPropertyName("dnstotcacheflush")]public string DnsTotalCacheFlush { get; set; }
        [JsonPropertyName("dnstotcacheentriesflush")]public string DnsTotalCacheEntriesFlush { get; set; }
        [JsonPropertyName("dnscurnoauthentries")]public string DnsCurrentNonAuthoritativeEntries { get; set; }
        [JsonPropertyName("dnscurauthentries")]public string DnsCurrentAuthoritativeEntries { get; set; }
        [JsonPropertyName("dnstotauthnonames")]public string DnsTotalQueriesNoRecords { get; set; }
        [JsonPropertyName("dnstotunsupportedresponseclass")]public string DnsTotalUnsupportedResponseClass { get; set; }
        [JsonPropertyName("dnstotinvalidqueryformat")]public string DnsTotalInvalidQueryFormat { get; set; }
        [JsonPropertyName("dnstotstrayanswer")]public string DnsTotalStrayAnswer { get; set; }
        [JsonPropertyName("dnstotresponsebadlen")]public string DnsTotalResponseBadLength { get; set; }
        [JsonPropertyName("dnstotreqrefusals")]public string DnsTotalRequestRefusals { get; set; }
        [JsonPropertyName("dnserrnullattack")]public string DnsErrorNullAttack { get; set; }
        [JsonPropertyName("dnstotunsupportedresponsetype")]public string DnsTotalUnsupportedResponseType { get; set; }
        [JsonPropertyName("dnstotunsupportedqueryclass")]public string DnsTotalUnsupportedQueryClass { get; set; }
        [JsonPropertyName("dnstotnonauthnodatas")]public string DnsTotalResponsesFormatError { get; set; } 
        [JsonPropertyName("dnstotnodataresps")]public string DnsTotalNoDataResponses { get; set; }
        [JsonPropertyName("dnstotmultiquerydisableerror")]public string DnsTotalMultiQueryDisableError { get; set; }
        [JsonPropertyName("dnstotothererrors")]public string DnsTotalOtherErrors { get; set; }
        [JsonPropertyName("dns64totqueries")]public string Dns64TotalQueries { get; set; }
        [JsonPropertyName("dns64queriesrate")]public double? Dns64QueriesRate { get; set; }
        [JsonPropertyName("dns64totanswers")]public string Dns64TotalAnswers { get; set; }
        [JsonPropertyName("dns64answersrate")]public double? Dns64AnswersRate { get; set; }
        [JsonPropertyName("dns64totrwanswers")]public string Dns64TotalReWriteAnswers { get; set; }
        [JsonPropertyName("dns64rwanswersrate")]public double? Dns64ReWriteAnswersRate { get; set; }
        [JsonPropertyName("dns64totresponses")]public string Dns64TotalResponses { get; set; }
        [JsonPropertyName("dns64responsesrate")]public double? Dns64ResponsesRate { get; set; }
        [JsonPropertyName("dns64totgslbqueries")]public string Dns64TotalGlobalServerLoadBalancingQueries { get; set; }
        [JsonPropertyName("dns64gslbqueriesrate")]public double? Dns64GlobalServerLoadBalancingQueriesRate { get; set; }
        [JsonPropertyName("dns64totgslbanswers")]public string Dns64TotalGlobalServerLoadBalancingAnswers { get; set; }
        [JsonPropertyName("dns64gslbanswersrate")]public double? Dns64GlobalServerLoadBalancingAnswersRate { get; set; }
        [JsonPropertyName("dns64tottcanswers")]public string Dns64TotalTcAnswers { get; set; }
        [JsonPropertyName("dns64tcanswersrate")]public double? Dns64TcAnswersRate { get; set; }
        [JsonPropertyName("dns64totsvraqueries")]public string Dns64TotalServerAQueries { get; set; } 
        [JsonPropertyName("dns64svraqueriesrate")]public double? Dns64ServerAQueriesRate { get; set; } 
        [JsonPropertyName("dns64totaaaabypass")]public string Dns64TotalAaaaBypass { get; set; }
        [JsonPropertyName("dns64aaaabypassrate")]public double? Dns64AaaaBypassRate { get; set; }
        [JsonPropertyName("dns64tottcpqueries")]public string Dns64TotalTcpQueries { get; set; }
        [JsonPropertyName("dns64tcpqueriesrate")]public double? Dns64TcpQueriesRate { get; set; }
        [JsonPropertyName("dns64activepolicies")]public string Dns64ActivePolicies { get; set; }
        [JsonPropertyName("dns64totnodataresp")]public string Dns64TotalNoDataResponse { get; set; }
        [JsonPropertyName("dns64nodataresprate")]public double? Dns64NoDataResponseRate { get; set; }
        [JsonPropertyName("dnstotnsrecqueries")]public string DnsTotalNsReceivedQueries { get; set; }
        [JsonPropertyName("dnsnsrecqueriesrate")]public double? DnsNsReceivedQueriesRate { get; set; }
        [JsonPropertyName("dnstotsoarecqueries")]public string DnsTotalSoaReceivedQueries { get; set; }
        [JsonPropertyName("dnssoarecqueriesrate")]public double? DnsSoaReceivedQueriesRate { get; set; }
        [JsonPropertyName("dnstotptrrecqueries")]public string DnsTotalPtrReceivedQueries { get; set; }
        [JsonPropertyName("dnsptrrecqueriesrate")]public double? DnsPtrReceivedQueriesRate { get; set; }
        [JsonPropertyName("dnstotsrvrecqueries")]public string DnsTotalSrvReceivedQueries { get; set; }
        [JsonPropertyName("dnssrvrecqueriesrate")]public double? DnsSrvReceivedQueriesRate { get; set; }
        [JsonPropertyName("dnstotaresponse")]public string DnsTotalAResponse { get; set; }
        [JsonPropertyName("dnsaresponserate")]public double? DnsAResponseRate { get; set; }
        [JsonPropertyName("dnstotcnameresponse")]public string DnsTotalCnameResponse { get; set; }
        [JsonPropertyName("dnscnameresponserate")]public double? DnsCnameResponseRate { get; set; }
        [JsonPropertyName("dnstotmxresponse")]public string DnsTotMxResponse { get; set; }
        [JsonPropertyName("dnsmxresponserate")]public double? DnsMxResponseRate { get; set; }
        [JsonPropertyName("dnstotanyresponse")]public string DnsTotalAnyResponse { get; set; }
        [JsonPropertyName("dnsanyresponserate")]public double? DnsAnyResponseRate { get; set; }
        [JsonPropertyName("dnstotnsrecupdate")]public string DnsTotalNsReceivedUpdate { get; set; }
        [JsonPropertyName("dnstotsoarecupdate")]public string DnsTotalSoaReceivedUpdate { get; set; }
        [JsonPropertyName("dnstotptrrecupdate")]public string DnsTotalPtrReceivedUpdate { get; set; }
        [JsonPropertyName("dnstotsrvrecupdate")]public string DnsTotalSrvReceivedUpdate { get; set; }
        [JsonPropertyName("dnstotaaaarecqueries")]public string DnsTotalAaaaReceivedQueries { get; set; }
        [JsonPropertyName("dnsaaaarecqueriesrate")]public double? DnsAaaaReceivedQueriesRate { get; set; }
        [JsonPropertyName("dnstotarecqueries")]public string DnsTotalAReceivedQueries { get; set; }
        [JsonPropertyName("dnsarecqueriesrate")]public double? DnsAReceivedQueriesRate { get; set; }
        [JsonPropertyName("dnstotcnamerecqueries")]public string DnsTotalCnameReceivedQueries { get; set; }
        [JsonPropertyName("dnscnamerecqueriesrate")]public double? DnsCnameReceivedQueriesRate { get; set; }
        [JsonPropertyName("dnstotmxrecqueries")]public string DnsTotalMxReceivedQueries { get; set; }
        [JsonPropertyName("dnsmxrecqueriesrate")]public double? DnsMxReceivedQueriesRate { get; set; }
        [JsonPropertyName("dnstotanyqueries")]public string DnsTotalAnyQueries { get; set; }
        [JsonPropertyName("dnsanyqueriesrate")]public double? DnsAnyQueriesRate { get; set; }
        [JsonPropertyName("dnstotaaaaresponse")]public string DnsTotalAaaaResponse { get; set; }
        [JsonPropertyName("dnsaaaaresponserate")]public double? DnsAaaaResponseRate { get; set; }
        [JsonPropertyName("dnstotnsresponse")]public string DnsTotalNsResponse { get; set; }
        [JsonPropertyName("dnsnsresponserate")]public double? DnsNsResponseRate { get; set; }
        [JsonPropertyName("dnstotsoaresponse")]public string DnsTotalSoaResponse { get; set; }
        [JsonPropertyName("dnssoaresponserate")]public double? DnsSoaResponseRate { get; set; }
        [JsonPropertyName("dnstotptrresponse")]public string DnsTotalPtrResponse { get; set; }
        [JsonPropertyName("dnsptrresponserate")]public double? DnsPtrResponseRate { get; set; }
        [JsonPropertyName("dnstotsrvresponse")]public string DnsTotalSrvResponse { get; set; }
        [JsonPropertyName("dnssrvresponserate")]public double? DnsSrvResponseRate { get; set; }
        [JsonPropertyName("dnstotaaaarecupdate")]public string DnsTotalAaaaReceivedUpdate { get; set; }
        [JsonPropertyName("dnstotarecupdate")]public string DnsTotalAReceivedUpdate { get; set; }
        [JsonPropertyName("dnstotmxrecupdate")]public string DnsTotalMxReceivedUpdate { get; set; }
        [JsonPropertyName("dnstotcnamerecupdate")]public string DnsTotalCnameReceivedUpdate { get; set; }
        [JsonPropertyName("dnscuraaaarecord")]public string DnsCurrentAaaaRecord { get; set; }
        [JsonPropertyName("dnscurarecord")]public string DnsCurrentARecord { get; set; }
        [JsonPropertyName("dnscurmxrecord")]public string DnsCurrentMxRecord { get; set; }
        [JsonPropertyName("dnscurcnamerecord")]public string DnsCurrentCnameRecord { get; set; }
        [JsonPropertyName("dnscurnsrecord")]public string DnsCurrentNsRecord { get; set; }
        [JsonPropertyName("dnscursoarecord")]public string DnsCurrentSoaRecord { get; set; }
        [JsonPropertyName("dnscurptrrecord")]public string DnsCurrentPtrRecord { get; set; }
        [JsonPropertyName("dnscursrvrecord")]public string DnsCurSrvRecord { get; set; }
        [JsonPropertyName("dnstotaaaarecfailed")]public string DnsTotalAaaaRecordFailed { get; set; }
        [JsonPropertyName("dnstotarecfailed")]public string DnsTotalARecordFailed { get; set; }
        [JsonPropertyName("dnstotmxrecfailed")]public string DnsTotalMxRecordFailed { get; set; }
        [JsonPropertyName("dnstotptrrecfailed")]public string DnsTotalPtrRecordFailed { get; set; }
        [JsonPropertyName("dnstotnsrecfailed")]public string DnsTotalNsRecordFailed { get; set; }
        [JsonPropertyName("dnstotcnamerecfailed")]public string DnsTotalCnameRecordFailed { get; set; }
        [JsonPropertyName("dnstotsoarecfailed")]public string DnsTotalSoaRecordFailed { get; set; }
        [JsonPropertyName("dnstotsrvrecfailed")]public string DnsTotalSrvRecordFailed { get; set; }
        [JsonPropertyName("dnstotanyrecfailed")]public string DnsTotalAnyRecordFailed { get; set; }
        [JsonPropertyName("dnstotunsupportedqueries")]public string DnsTotalUnsupportedQueries { get; set; }
    }
}