using System.Text.Json.Serialization;

namespace CoreLayer.Citrix.Adc.NitroData.Api.Statistics.AppFirewall
{
    public class AppFwStats
    {
        [JsonPropertyName("appfirewalltotallog")]public string AppFirewallTotalLog { get; set; }    
        [JsonPropertyName("appfirewalllograte")]public double? AppFirewallLogRate { get; set; }    
        [JsonPropertyName("appfirewalltotalviol")]public string AppFirewallTotalViolation { get; set; }    
        [JsonPropertyName("appfirewallviolrate")]public double? AppFirewallViolationRate { get; set; }    
        [JsonPropertyName("appfirewallshortavgresptime")]public string AppFirewallShortAverageResponseTime { get; set; }    
        [JsonPropertyName("appfirewalllongavgresptime")]public string AppFirewallLongAverageResponseTime { get; set; }    
        [JsonPropertyName("appfirewallrequests")]public string AppFirewallRequests { get; set; }    
        [JsonPropertyName("appfirewallrequestsrate")]public double? AppFirewallRequestsRate { get; set; }    
        [JsonPropertyName("appfirewallreqbytes")]public string AppFirewallRequestBytes { get; set; }    
        [JsonPropertyName("appfirewallreqbytesrate")]public double? AppFirewallRequestBytesRate { get; set; }    
        [JsonPropertyName("appfirewallresponses")]public string AppFirewallResponses { get; set; }    
        [JsonPropertyName("appfirewallresponsesrate")]public double? AppFirewallResponsesRate { get; set; }    
        [JsonPropertyName("appfirewallresbytes")]public string AppFirewallResponseBytes { get; set; }    
        [JsonPropertyName("appfirewallresbytesrate")]public double? AppFirewallResponseBytesRate { get; set; }    
        [JsonPropertyName("appfirewallaborts")]public string AppFirewallAborts { get; set; }    
        [JsonPropertyName("appfirewallabortsrate")]public double? AppFirewallAbortsRate { get; set; }    
        [JsonPropertyName("appfirewallredirects")]public string AppFirewallRedirects { get; set; }    
        [JsonPropertyName("appfirewallredirectsrate")]public double? AppFirewallRedirectsRate { get; set; }    
        [JsonPropertyName("appfirewalltrapsdropped")]public string AppFirewallTrapsDropped { get; set; }    
        [JsonPropertyName("appfirewallviolstarturl")]public string AppFirewallViolationStartUrl { get; set; }    
        [JsonPropertyName("appfirewallviolstarturlrate")]public double? AppFirewallViolateStartUrlRate { get; set; }    
        [JsonPropertyName("appfirewallvioldenyurl")]public string AppFirewallViolationDenyUrl { get; set; }    
        [JsonPropertyName("appfirewallvioldenyurlrate")]public double? AppFirewallViolationDenyUrlRate { get; set; }    
        [JsonPropertyName("appfirewallviolrefererheader")]public string AppFirewallViolationRefererHeader { get; set; }    
        [JsonPropertyName("appfirewallviolrefererheaderrate")]public double? AppFirewallViolationRefererHeaderRate { get; set; }    
        [JsonPropertyName("appfirewallviolbufferoverflow")]public string AppFirewallViolationBufferOverflow { get; set; }    
        [JsonPropertyName("appfirewallviolbufferoverflowrate")]public double? AppFirewallViolationBufferOverflowRate { get; set; }    
        [JsonPropertyName("appfirewallviolcookie")]public string AppFirewallViolationCookie { get; set; }    
        [JsonPropertyName("appfirewallviolcookierate")]public double? AppFirewallViolationCookieRate { get; set; }    
        [JsonPropertyName("appfirewallviolcsrftag")]public string AppFirewallViolationCrossSiteRequestForgeryTag { get; set; }    
        [JsonPropertyName("appfirewallviolcsrftagrate")]public double? AppFirewallViolationCrossSiteRequestForgeryTagRate { get; set; }    
        [JsonPropertyName("appfirewallviolxss")]public string AppFirewallViolationCrossSiteScripting { get; set; }    
        [JsonPropertyName("appfirewallviolxssrate")]public double? AppFirewallViolationCrossSiteScriptingRate { get; set; }    
        [JsonPropertyName("appfirewallviolsql")]public string AppFirewallViolationSqlInjection { get; set; }    
        [JsonPropertyName("appfirewallviolsqlrate")]public double? AppFirewallViolationSqlInjectionRate { get; set; }    
        [JsonPropertyName("appfirewallviolfieldformat")]public string AppFirewallViolationFieldFormat { get; set; }    
        [JsonPropertyName("appfirewallviolfieldformatrate")]public double? AppFirewallViolationFieldFormatRate { get; set; }    
        [JsonPropertyName("appfirewallviolfieldconsistency")]public string AppFirewallViolationFieldConsistency { get; set; }    
        [JsonPropertyName("appfirewallviolfieldconsistencyrate")]public double? AppFirewallViolationFieldConsistencyRate { get; set; }    
        [JsonPropertyName("appfirewallviolfileuploadtypes")]public string AppFirewallViolationFileUploadTypes { get; set; }    
        [JsonPropertyName("appfirewallviolfileuploadtypesrate")]public double? AppFirewallViolationFileUploadTypesRate { get; set; }    
        [JsonPropertyName("appfirewallviolcreditcard")]public string AppFirewallViolationCreditCard { get; set; }    
        [JsonPropertyName("appfirewallviolcreditcardrate")]public double? AppFirewallViolationCreditCardRate { get; set; }    
        [JsonPropertyName("appfirewallviolsafeobject")]public string AppFirewallViolationSafeObject { get; set; }    
        [JsonPropertyName("appfirewallviolsafeobjectrate")]public double? AppFirewallViolationSafeObjectRate { get; set; }    
        [JsonPropertyName("appfirewallviolsignature")]public string AppFirewallViolationSignature { get; set; }    
        [JsonPropertyName("appfirewallviolsignaturerate")]public double? AppFirewallViolationSignatureRate { get; set; }    
        [JsonPropertyName("appfirewallviolcontenttype")]public string AppFirewallViolationContentType { get; set; }    
        [JsonPropertyName("appfirewallviolcontenttyperate")]public double? AppFirewallViolationContentTypeRate { get; set; }    
        [JsonPropertyName("appfirewallvioljsondos")]public string AppFirewallViolationJsonDenialOfService { get; set; }    
        [JsonPropertyName("appfirewallvioljsondosrate")]public double? AppFirewallViolationJsonDenialOfServiceRate { get; set; }    
        [JsonPropertyName("appfirewallvioljsonsql")]public string AppFirewallViolationJsonSql { get; set; }    
        [JsonPropertyName("appfirewallvioljsonsqlrate")]public double? AppFirewallViolationJsonSqlRate { get; set; }    
        [JsonPropertyName("appfirewallvioljsonxss")]public string AppFirewallViolationJsonCrossSiteScripting { get; set; }    
        [JsonPropertyName("appfirewallvioljsonxssrate")]public double? AppFirewallViolationJsonCrossSiteScriptingRate { get; set; }    
        [JsonPropertyName("appfirewallviolwellformednessviolations")]public string AppFirewallViolationWellFormednessViolations { get; set; }    
        [JsonPropertyName("appfirewallviolwellformednessviolationsrate")]public double? AppFirewallViolationWellFormednessViolationsRate { get; set; }    
        [JsonPropertyName("appfirewallviolxdosviolations")]public string AppFirewallViolationXmlDenialOfServiceViolations { get; set; }    
        [JsonPropertyName("appfirewallviolxdosviolationsrate")]public double? AppFirewallViolationXmlDenialOfServiceViolationsRate { get; set; }    
        [JsonPropertyName("appfirewallviolmsgvalviolations")]public string AppFirewallViolationMessageValidationViolations { get; set; }    
        [JsonPropertyName("appfirewallviolmsgvalviolationsrate")]public double? AppFirewallViolationMessageValidationViolationsRate { get; set; }    
        [JsonPropertyName("appfirewallviolwsiviolations")]public string AppFirewallViolationWebServicesInteroperabilityViolations { get; set; }    
        [JsonPropertyName("appfirewallviolwsiviolationsrate")]public double? AppFirewallViolationWebServicesInteroperabilityViolationsRate { get; set; }    
        [JsonPropertyName("appfirewallviolxmlsqlviolations")]public string AppFirewallViolationXmlSqlViolations { get; set; }    
        [JsonPropertyName("appfirewallviolxmlsqlviolationsrate")]public double? AppFirewallViolationXmlSqlViolationsRate { get; set; }    
        [JsonPropertyName("appfirewallviolxmlxssviolations")]public string AppFirewallViolationXmlCrossSiteScriptingViolations { get; set; }    
        [JsonPropertyName("appfirewallviolxmlxssviolationsrate")]public double? AppFirewallViolationXmlCrossSiteScriptingViolationsRate { get; set; }    
        [JsonPropertyName("appfirewallviolxmlattachmentviolations")]public string AppFirewallViolationXmlAttachmentViolations { get; set; }    
        [JsonPropertyName("appfirewallviolxmlattachmentviolationsrate")]public double? AppFirewallViolXmlAttachmentViolationsRate { get; set; }    
        [JsonPropertyName("appfirewallviolxmlsoapfaultviolations")]public string AppFirewallViolationXmlSoapFaultViolations { get; set; }    
        [JsonPropertyName("appfirewallviolxmlsoapfaultviolationsrate")]public double? AppFirewallViolationXmlSoapFaultViolationsRate { get; set; }    
        [JsonPropertyName("appfirewallviolxmlgenviolations")]public string AppFirewallViolationXmlGenericViolations { get; set; }    
        [JsonPropertyName("appfirewallviolxmlgenviolationsrate")]public double? AppFirewallViolationXmlGenericViolationsRate { get; set; }    
        [JsonPropertyName("appfirewalllogstarturl")]public string AppFirewallLogStartUrl { get; set; }    
        [JsonPropertyName("appfirewalllogstarturlrate")]public double? AppFirewallLogStartUrlRate { get; set; }    
        [JsonPropertyName("appfirewalllogdenyurl")]public string AppFirewallLogDenyUrl { get; set; }    
        [JsonPropertyName("appfirewalllogdenyurlrate")]public double? AppFirewallLogDenyUrlRate { get; set; }    
        [JsonPropertyName("appfirewalllogrefererheader")]public string AppFirewallLogRefererHeader { get; set; }    
        [JsonPropertyName("appfirewalllogrefererheaderrate")]public double? AppFirewallLogRefererHeaderRate { get; set; }    
        [JsonPropertyName("appfirewalllogbufferoverflow")]public string AppFirewallLogBufferOverflow { get; set; }    
        [JsonPropertyName("appfirewalllogbufferoverflowrate")]public double? AppFirewallLogBufferOverflowRate { get; set; }    
        [JsonPropertyName("appfirewalllogcookie")]public string AppFirewallLogCookie { get; set; }    
        [JsonPropertyName("appfirewalllogcookierate")]public double? AppFirewallLogCookieRate { get; set; }    
        [JsonPropertyName("appfirewalllogcsrftag")]public string AppFirewallLogCrossSiteRequestForgeryTag { get; set; }    
        [JsonPropertyName("appfirewalllogcsrftagrate")]public double? AppFirewallLogCrossSiteRequestForgeryTagRate { get; set; }    
        [JsonPropertyName("appfirewalllogxss")]public string AppFirewallLogCrossSiteScripting { get; set; }    
        [JsonPropertyName("appfirewalllogxssrate")]public double? AppFirewallLogCrossSiteScriptingRate { get; set; }    
        [JsonPropertyName("appfirewalllogtransformxss")]public string AppFirewallLogTransformCrossSiteScripting { get; set; }    
        [JsonPropertyName("appfirewalllogtransformxssrate")]public double? AppFirewallLogTransformCrossSiteScriptingRate { get; set; }    
        [JsonPropertyName("appfirewalllogsql")]public string AppFirewallLogSqlInjection { get; set; }    
        [JsonPropertyName("appfirewalllogsqlrate")]public double? AppFirewallLogSqlInjectionRate { get; set; }    
        [JsonPropertyName("appfirewalllogtransformsql")]public string AppFirewallLogTransformSqlInjection { get; set; }    
        [JsonPropertyName("appfirewalllogtransformsqlrate")]public double? AppFirewallLogTransformSqlInjectionRate { get; set; }    
        [JsonPropertyName("appfirewalllogfieldformat")]public string AppFirewallLogFieldFormat { get; set; }    
        [JsonPropertyName("appfirewalllogfieldformatrate")]public double? AppFirewallLogFieldFormatRate { get; set; }    
        [JsonPropertyName("appfirewalllogfieldconsistency")]public string AppFirewallLogFieldConsistency { get; set; }    
        [JsonPropertyName("appfirewalllogfieldconsistencyrate")]public double? AppFirewallLogFieldConsistencyRate { get; set; }    
        [JsonPropertyName("appfirewalllogcreditcard")]public string AppFirewallLogCreditCard { get; set; }    
        [JsonPropertyName("appfirewalllogcreditcardrate")]public double? AppFirewallLogCreditCardRate { get; set; }    
        [JsonPropertyName("appfirewalllogsafeobject")]public string AppFirewallLogSafeObject { get; set; }    
        [JsonPropertyName("appfirewalllogsafeobjectrate")]public double? AppFirewallLogSafeObjectRate { get; set; }    
        [JsonPropertyName("appfirewallsignaturelogs")]public string AppFirewallSignatureLogs { get; set; }    
        [JsonPropertyName("appfirewallsignaturelogsrate")]public double? AppFirewallSignatureLogsRate { get; set; }    
        [JsonPropertyName("appfirewalllogcontenttype")]public string AppFirewallLogContentType { get; set; }    
        [JsonPropertyName("appfirewalllogcontenttyperate")]public double? AppFirewallLogContentTypeRate { get; set; }    
        [JsonPropertyName("appfirewalllogsjsondos")]public string AppFirewallLogsJsonDenialOfService { get; set; }    
        [JsonPropertyName("appfirewalllogsjsondosrate")]public double? AppFirewallLogsJsonDenialOfServiceRate { get; set; }    
        [JsonPropertyName("appfirewalllogsjsonsql")]public string AppFirewallLogsJsonSqlInjection { get; set; }    
        [JsonPropertyName("appfirewalllogsjsonsqlrate")]public double? AppFirewallLogsJsonSqlInjectionRate { get; set; }    
        [JsonPropertyName("appfirewalllogsjsonxss")]public string AppFirewallLogsJsonCrossSiteScripting { get; set; }    
        [JsonPropertyName("appfirewalllogsjsonxssrate")]public double? AppFirewallLogsJsonCrossSiteScriptingRate { get; set; }    
        [JsonPropertyName("appfirewalllogfileuploadtypes")]public string AppFirewallLogFileUploadTypes { get; set; }    
        [JsonPropertyName("appfirewalllogfileuploadtypesrate")]public double? AppFirewallLogFileUploadTypesRate { get; set; }    
        [JsonPropertyName("appfirewallwellformednesslogs")]public string AppFirewallWellFormednessLogs { get; set; }    
        [JsonPropertyName("appfirewallwellformednesslogsrate")]public double? AppFirewallWellFormednessLogsRate { get; set; }    
        [JsonPropertyName("appfirewallxdoslogs")]public string AppFirewallXmlDenialOfServiceLogs { get; set; }    
        [JsonPropertyName("appfirewallxdoslogsrate")]public double? AppFirewallXmlDnialOfServiceLogsRate { get; set; }    
        [JsonPropertyName("appfirewallmsgvallogs")]public string AppFirewallMessageValidationLogs { get; set; }    
        [JsonPropertyName("appfirewallmsgvallogsrate")]public double? AppFirewallMessageValidationLogsRate { get; set; }    
        [JsonPropertyName("appfirewallwsilogs")]public string AppFirewallWebServicesInteroperabilityLogs { get; set; }    
        [JsonPropertyName("appfirewallwsilogsrate")]public double? AppFirewallWebServicesInteroperabilityLogsRate { get; set; }    
        [JsonPropertyName("appfirewallxmlsqllogs")]public string AppFirewallXmlSqlInjectionLogs { get; set; }    
        [JsonPropertyName("appfirewallxmlsqllogsrate")]public double? AppFirewallXmlSqlInjectionLogsRate { get; set; }    
        [JsonPropertyName("appfirewallxmlxsslogs")]public string AppFirewallXmlCrossSiteScriptingLogs { get; set; }    
        [JsonPropertyName("appfirewallxmlxsslogsrate")]public double? AppFirewallXmlCrossSiteScriptingLogsRate { get; set; }    
        [JsonPropertyName("appfirewallxmlattachmentlogs")]public string AppFirewallXmlAttachmentLogs { get; set; }    
        [JsonPropertyName("appfirewallxmlattachmentlogsrate")]public double? AppFirewallXmlAttachmentLogsRate { get; set; }    
        [JsonPropertyName("appfirewallxmlsoapfaultlogs")]public string AppFirewallXmlSoapFaultLogs { get; set; }    
        [JsonPropertyName("appfirewallxmlsoapfaultlogsrate")]public double? AppFirewallXmlSoapFaultLogsRate { get; set; }    
        [JsonPropertyName("appfirewallxmlgenlogs")]public string AppFirewallXmlGenericLogs { get; set; }    
        [JsonPropertyName("appfirewallxmlgenlogsrate")]public double? AppFirewallXmlGenericLogsRate { get; set; }    
        [JsonPropertyName("appfirewallret4xx")]public string AppFirewallReturning4xx { get; set; }    
        [JsonPropertyName("appfirewallret4xxrate")]public double? AppFirewallRetruning4xxRate { get; set; }    
        [JsonPropertyName("appfirewallret5xx")]public string AppFirewallReturning5xx { get; set; }    
        [JsonPropertyName("appfirewallret5xxrate")]public double? AppFirewallReturning5xxRate { get; set; }
    }
}