using System.Text.Json.Serialization;

namespace CoreLayer.Citrix.Adc.NitroData.Api.Configuration.ContentSwitching
{
    public class CsvserverConfiguration : ICsvserverConfiguration
    {
        public string Name { get; set; }
        public string Td { get; set; }
        public string ServiceType { get; set; }
        public string IpV46 { get; set; }
        public string TargetType { get; set; }
        public string DnsRecordType { get; set; }
        public string PersistenceId { get; set; }
        public string IpPattern { get; set; }
        public string IpMask { get; set; }
        public string Range { get; set; }
        public int? Port { get; set; }
        public string State { get; set; }
        public string StateUpdate { get; set; }
        public string Cacheable { get; set; }
        public string RedirectUrl { get; set; }
        public string CltTimeout { get; set; }
        public string Precedence { get; set; }
        public string CaseSensitive { get; set; }
        public string SoMethod { get; set; }
        public string SoPersistence { get; set; }
        public string SoPersistenceTimeout { get; set; }
        public string SoThreshold { get; set; }
        public string SoBackupAction { get; set; }
        public string RedirectPortRewrite { get; set; }
        public string DownStateFlush { get; set; }
        public string BackupVserver { get; set; }
        public string DisablePrimaryOnDown { get; set; }
        public string InsertVserverIpPort { get; set; }
        public string VipHeader { get; set; }
        public string RtspNat { get; set; }
        public string AuthenticationHost { get; set; }
        public string Authentication { get; set; }
        public string ListenPolicy { get; set; }
        public string ListenPriority { get; set; }
        public string Authn401 { get; set; }
        public string AuthnVsName { get; set; }
        public string Push { get; set; }
        public string PushVServer { get; set; }
        public string PushLabel { get; set; }
        public string PushMultiClients { get; set; }
        public string TcpProfileName { get; set; }
        public string HttpProfileName { get; set; }
        public string DbProfileName { get; set; }
        public string OracleServerVersion { get; set; }
        public string Comment { get; set; }
        public string MsSqlServerVersion { get; set; }
        public string L2Conn { get; set; }
        public string MySqlProtocolVersion { get; set; }
        public string MySqlServerVersion { get; set; }
        public string MySqlCharacterSet { get; set; }
        public string MySqlServerCapabilities { get; set; }
        public string AppFlowLog { get; set; }
        public string NetProfile { get; set; }
        public string IcmpVsrResponse { get; set; }
        public string RhiState { get; set; }
        public string AuthnProfile { get; set; }
        public string DnsProfileName { get; set; }
        public string DomainName { get; set; }
        public double? Ttl { get; set; }
        public string BackupIp { get; set; }
        public string CookieDomain { get; set; }
        public double? CookieTimeout { get; set; }
        public double? SiteDomainTtl { get; set; }
        public string NewName { get; set; }
        public string Ip { get; set; }
        public string Value { get; set; }
        public string NgName { get; set; }
        public string Type { get; set; }
        public string CurState { get; set; }
        public string Sc { get; set; }
        public int? Status { get; set; }
        public string CacheType { get; set; }
        public string Redirect { get; set; }
        public string HomePage { get; set; }
        public string DnsVserverName { get; set; }
        public string Domain { get; set; }
        public string PolicyName { get; set; }
        public string ServiceName { get; set; }
        public string Weight { get; set; }
        public string CacheVserver { get; set; }
        public string TargetVserver { get; set; }
        public string Priority { get; set; }
        public string Url { get; set; }
        public string GoToPriorityExpression { get; set; }
        public string BindPoint { get; set; }
        public bool? Invoke { get; set; }
        public string LabelType { get; set; }
        public string LabelName { get; set; }
        public string Gt2Gb { get; set; }
        public string StateChangeTimeSec { get; set; }
        public string StateChangeTimeMSec { get; set; }
        public string TicksSinceLastStateChange { get; set; }
        public string RuleType { get; set; }
        public string LbvServer { get; set; }
        public string TargetLbvserver { get; set; }
        [JsonPropertyName("__count")]public double? Count { get; set; }
    }
}