namespace CoreLayer.Citrix.Adc.NitroData.Api.Configuration.ContentSwitching
{
    public interface ICsvserverConfiguration
    {
        string Name { get; set; }
        string Td { get; set; } 
        string ServiceType { get; set; }
        string IpV46 { get; set; } 
        string TargetType { get; set; }
        string DnsRecordType { get; set; }
        string PersistenceId { get; set; }
        string IpPattern { get; set; }
        string IpMask { get; set; }
        string Range { get; set; }
        int? Port { get; set; }
        string State { get; set; }
        string StateUpdate { get; set; }
        string Cacheable { get; set; }
        string RedirectUrl { get; set; }
        string CltTimeout { get; set; } 
        string Precedence { get; set; }
        string CaseSensitive { get; set; }
        string SoMethod { get; set; } 
        string SoPersistence { get; set; } 
        string SoPersistenceTimeout { get; set; } 
        string SoThreshold { get; set; } 
        string SoBackupAction { get; set; } 
        string RedirectPortRewrite { get; set; }
        string DownStateFlush { get; set; }
        string BackupVserver { get; set; } 
        string DisablePrimaryOnDown { get; set; } 
        string InsertVserverIpPort { get; set; }
        string VipHeader { get; set; } 
        string RtspNat { get; set; } 
        string AuthenticationHost { get; set; }
        string Authentication { get; set; }
        string ListenPolicy { get; set; }
        string ListenPriority { get; set; }
        string Authn401 { get; set; } 
        string AuthnVsName { get; set; } 
        string Push { get; set; }
        string PushVServer { get; set; }
        string PushLabel { get; set; }
        string PushMultiClients { get; set; }
        string TcpProfileName { get; set; }
        string HttpProfileName { get; set; }
        string DbProfileName { get; set; }
        string OracleServerVersion { get; set; }
        string Comment { get; set; }
        string MsSqlServerVersion { get; set; }
        string L2Conn { get; set; } 
        string MySqlProtocolVersion { get; set; }
        string MySqlServerVersion { get; set; }
        string MySqlCharacterSet { get; set; }
        string MySqlServerCapabilities { get; set; }
        string AppFlowLog { get; set; } 
        string NetProfile { get; set; }
        string IcmpVsrResponse { get; set; } 
        string RhiState { get; set; } 
        string AuthnProfile { get; set; } 
        string DnsProfileName { get; set; }
        string DomainName { get; set; }
        double? Ttl { get; set; } 
        string BackupIp { get; set; }
        string CookieDomain { get; set; }
        double? CookieTimeout { get; set; }
        double? SiteDomainTtl { get; set; } 
        string NewName { get; set; }
        string Ip { get; set; }
        string Value { get; set; }
        string NgName { get; set; } 
        string Type { get; set; }
        string CurState { get; set; } 
        string Sc { get; set; } 
        int? Status { get; set; }
        string CacheType { get; set; }
        string Redirect { get; set; }
        string HomePage { get; set; }
        string DnsVserverName { get; set; }
        string Domain { get; set; }
        string PolicyName { get; set; }
        string ServiceName { get; set; }
        string Weight { get; set; }
        string CacheVserver { get; set; }
        string TargetVserver { get; set; }
        string Priority { get; set; }
        string Url { get; set; }
        string GoToPriorityExpression { get; set; }
        string BindPoint { get; set; }
        bool? Invoke { get; set; }
        string LabelType { get; set; }
        string LabelName { get; set; }
        string Gt2Gb { get; set; } 
        string StateChangeTimeSec { get; set; }
        string StateChangeTimeMSec { get; set; }
        string TicksSinceLastStateChange { get; set; }
        string RuleType { get; set; }
        string LbvServer { get; set; }
        string TargetLbvserver { get; set; }
        double? Count { get; set; } //[JsonPropertyName("__count")]
    }
}