namespace CoreLayer.Citrix.Adc.NitroData.Api.Configuration.LoadBalancing
{
    public interface ILbmonitorConfiguration
    {
        string MonitorName { get; set; }
        string Type { get; set; }
        string Action { get; set; }
        string[] RespCode { get; set; } 
        string HttpRequest { get; set; }
        string RtspRequest { get; set; }
        string CustomHeaders { get; set; }
        string MaxForwards { get; set; }
        string SipMethod { get; set; } 
        string SipUri { get; set; }
        string SipRegUri { get; set; }
        string Send { get; set; }
        string Recv { get; set; } 
        string Query { get; set; }
        string QueryType { get; set; }
        string ScriptName { get; set; }
        string ScriptArgs { get; set; }
        string DispatcherIp { get; set; }
        int? DispatcherPort { get; set; }
        string UserName { get; set; }
        string Password { get; set; }
        string SecondaryPassword { get; set; }
        string LogonPointName { get; set; }
        string LasVersion { get; set; }
        string RadKey { get; set; }
        string RadNasId { get; set; } 
        string RadNasIp { get; set; } 
        string RadAccountType { get; set; }
        string RadFramedIp { get; set; }
        string RadApn { get; set; }
        string RadMsisdn { get; set; }
        string RadAccountSession { get; set; }
        string Lrtm { get; set; } 
        string Deviation { get; set; }
        string Units1 { get; set; } 
        int? Interval { get; set; }
        string Units3 { get; set; } 
        int? RespTimeout { get; set; } 
        string Units4 { get; set; } 
        string RespTimeoutThresh { get; set; } 
        int? Retries { get; set; }
        int? FailureRetries { get; set; }
        int? AlertRetries { get; set; }
        int? SuccessRetries { get; set; }
        int? DownTime { get; set; }
        string Units2 { get; set; } 
        string DestIp { get; set; } 
        int? DestPort { get; set; }
        string State { get; set; }
        string Reverse { get; set; }
        string Transparent { get; set; }
        string IpTunnel { get; set; }
        string Tos { get; set; } 
        double? TosId { get; set; } 
        string Secure { get; set; }
        string ValidateCred { get; set; }
        string Domain { get; set; }
        string[] IpAddress { get; set; }
        string Group { get; set; }
        string FileName { get; set; }
        string BaseDn { get; set; } 
        string BindDn { get; set; } 
        string Filter { get; set; }
        string Attribute { get; set; }
        string DataBase { get; set; }
        string OracleSId { get; set; } 
        string SqlQuery { get; set; }
        string EvalRule { get; set; } 
        string MsSqlProtocolVersion { get; set; }
        string SnmpOid { get; set; }
        string SnmpCommunity { get; set; }
        string SnmpThreshold { get; set; }
        string SnmpVersion { get; set; }
        string MetricTable { get; set; }
        string Application { get; set; }
        string SitePath { get; set; }
        string StoreName { get; set; }
        string StoreFrontAcctService { get; set; }
        string HostName { get; set; }
        string NetProfile { get; set; }
        string OriginHost { get; set; }
        string OriginRealm { get; set; }
        string HostIpAddress { get; set; }
        string VendorId { get; set; }
        string ProductName { get; set; }
        string FirmwareVersion { get; set; }
        double[] AuthApplicationId { get; set; }
        double[] AcctApplicationId { get; set; } 
        string InBandSecurityId { get; set; }
        double[] SupportedVendorIds { get; set; }
        string VendorSpecificVendorId { get; set; }
        double[] VendorSpecificAuthApplicationIds { get; set; }
        double[] VendorSpecificAcctApplicationIds { get; set; }
        string KdcAccount { get; set; }
        string StoreDb { get; set; }
        string StoreFrontCheckBackendServices { get; set; }
        string TrofsCode { get; set; }
        string TrofsString { get; set; }
        string SslProfile { get; set; }
        string Metric { get; set; }
        string MetricThreshold { get; set; }
        string MetricWeight { get; set; }
        string ServiceName { get; set; }
        string ServicegroupName { get; set; }
        int? LrtmConf { get; set; } 
        string LrtmConfStr { get; set; } 
        int? DynamicResponseTimeout { get; set; }
        int? DynamicInterval { get; set; }
        string[] MultiMetricTable { get; set; }
        string DupState { get; set; } //[JsonPropertyName("dup_state")]
        string DupWeight { get; set; } //[JsonPropertyName("dup_weight")]
        string Weight { get; set; }
        bool? Ca { get; set; }
        double? Count { get; set; } //[JsonPropertyName("__count")]
        }
}