using System.Text.Json.Serialization;

namespace CoreLayer.Citrix.Adc.NitroData.Api.Configuration.LoadBalancing
{
    public class LbmonitorConfiguration : ILbmonitorConfiguration
    {
        public string MonitorName { get; set; }
        public string Type { get; set; }
        public string Action { get; set; }
        public string[] RespCode { get; set; }
        public string HttpRequest { get; set; }
        public string RtspRequest { get; set; }
        public string CustomHeaders { get; set; }
        public string MaxForwards { get; set; }
        public string SipMethod { get; set; }
        public string SipUri { get; set; }
        public string SipRegUri { get; set; }
        public string Send { get; set; }
        public string Recv { get; set; }
        public string Query { get; set; }
        public string QueryType { get; set; }
        public string ScriptName { get; set; }
        public string ScriptArgs { get; set; }
        public string DispatcherIp { get; set; }
        public int? DispatcherPort { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string SecondaryPassword { get; set; }
        public string LogonPointName { get; set; }
        public string LasVersion { get; set; }
        public string RadKey { get; set; }
        public string RadNasId { get; set; }
        public string RadNasIp { get; set; }
        public string RadAccountType { get; set; }
        public string RadFramedIp { get; set; }
        public string RadApn { get; set; }
        public string RadMsisdn { get; set; }
        public string RadAccountSession { get; set; }
        public string Lrtm { get; set; }
        public string Deviation { get; set; }
        public string Units1 { get; set; }
        public int? Interval { get; set; }
        public string Units3 { get; set; }
        public int? RespTimeout { get; set; }
        public string Units4 { get; set; }
        public string RespTimeoutThresh { get; set; }
        public int? Retries { get; set; }
        public int? FailureRetries { get; set; }
        public int? AlertRetries { get; set; }
        public int? SuccessRetries { get; set; }
        public int? DownTime { get; set; }
        public string Units2 { get; set; }
        public string DestIp { get; set; }
        public int? DestPort { get; set; }
        public string State { get; set; }
        public string Reverse { get; set; }
        public string Transparent { get; set; }
        public string IpTunnel { get; set; }
        public string Tos { get; set; }
        public double? TosId { get; set; }
        public string Secure { get; set; }
        public string ValidateCred { get; set; }
        public string Domain { get; set; }
        public string[] IpAddress { get; set; }
        public string Group { get; set; }
        public string FileName { get; set; }
        public string BaseDn { get; set; }
        public string BindDn { get; set; }
        public string Filter { get; set; }
        public string Attribute { get; set; }
        public string DataBase { get; set; }
        public string OracleSId { get; set; }
        public string SqlQuery { get; set; }
        public string EvalRule { get; set; }
        public string MsSqlProtocolVersion { get; set; }
        public string SnmpOid { get; set; }
        public string SnmpCommunity { get; set; }
        public string SnmpThreshold { get; set; }
        public string SnmpVersion { get; set; }
        public string MetricTable { get; set; }
        public string Application { get; set; }
        public string SitePath { get; set; }
        public string StoreName { get; set; }
        public string StoreFrontAcctService { get; set; }
        public string HostName { get; set; }
        public string NetProfile { get; set; }
        public string OriginHost { get; set; }
        public string OriginRealm { get; set; }
        public string HostIpAddress { get; set; }
        public string VendorId { get; set; }
        public string ProductName { get; set; }
        public string FirmwareVersion { get; set; }
        public double[] AuthApplicationId { get; set; }
        public double[] AcctApplicationId { get; set; }
        public string InBandSecurityId { get; set; }
        public double[] SupportedVendorIds { get; set; }
        public string VendorSpecificVendorId { get; set; }
        public double[] VendorSpecificAuthApplicationIds { get; set; }
        public double[] VendorSpecificAcctApplicationIds { get; set; }
        public string KdcAccount { get; set; }
        public string StoreDb { get; set; }
        public string StoreFrontCheckBackendServices { get; set; }
        public string TrofsCode { get; set; }
        public string TrofsString { get; set; }
        public string SslProfile { get; set; }
        public string Metric { get; set; }
        public string MetricThreshold { get; set; }
        public string MetricWeight { get; set; }
        public string ServiceName { get; set; }
        public string ServicegroupName { get; set; }
        public int? LrtmConf { get; set; }
        public string LrtmConfStr { get; set; }
        public int? DynamicResponseTimeout { get; set; }
        public int? DynamicInterval { get; set; }
        public string[] MultiMetricTable { get; set; }
        [JsonPropertyName("dup_state")]public string DupState { get; set; }
        [JsonPropertyName("dup_weight")]public string DupWeight { get; set; }
        public string Weight { get; set; }
        public bool? Ca { get; set; }
        [JsonPropertyName("__count")]public double? Count { get; set; }
    }
}