using System.Text.Json.Serialization;

namespace CoreLayer.Citrix.Adc.NitroData.Api.Statistics.Ssl
{
    public class SslStats
    {
        [JsonPropertyName("ssltothwdecbesecondary")]public string SslTotalHardwareBytesDecryptedBackEndSecondary { get; set; }    
        [JsonPropertyName("sslhwdecbesecondaryrate")]public double? SslHardwareBytesDecryptedBackEndSecondaryRate { get; set; }    
        [JsonPropertyName("ssltothwdecfesecondary")]public string SslTotalHardwareBytesDecryptedFrontEndSecondary { get; set; }    
        [JsonPropertyName("sslhwdecfesecondaryrate")]public double? SslHardwareBytesDecryptedFrontEndSecondaryRate { get; set; }    
        [JsonPropertyName("ssltothwencbesecondary")]public string SslTotalHardwareBytesEncryptedBackEndSecondary { get; set; }    
        [JsonPropertyName("sslhwencbesecondaryrate")]public double? SslHardwareBytesEncryptedBackEndSecondaryRate { get; set; }    
        [JsonPropertyName("ssltothwencfesecondary")]public string SslTotalHardwareBytesEncryptedFrontEndSecondary { get; set; }    
        [JsonPropertyName("sslhwencfesecondaryrate")]public double? SslHardwareBytesEncryptedFrontEndSecondaryRate { get; set; }    
        [JsonPropertyName("ssltotdechwsecondary")]public string SslTotalBytesDecryptedHardwareSecondary { get; set; }    
        [JsonPropertyName("ssldechwsecondaryrate")]public double? SslBytesDecryptedHardwareSecondaryRate { get; set; }    
        [JsonPropertyName("ssltotenchwsecondary")]public string SslTotalBytesEncryptedHardwareSecondary { get; set; }    
        [JsonPropertyName("sslenchwsecondaryrate")]public double? SslBytesEncryptedHardwareSecondaryRate { get; set; }    
        [JsonPropertyName("sslcryptoutilizationsymmstat")]public string SslCryptoUtilizationSymmetricStat { get; set; }    
        [JsonPropertyName("sslcryptoutilizationasymstat")]public string SslCryptoUtilizationAsymmetricStat { get; set; }    
        [JsonPropertyName("sslcryptoutilizationstat2nd")]public double? SslCryptoUtilizationStat { get; set; }    
        [JsonPropertyName("sslcryptoutilizationstat")]public double? SslCryptoUtilizationStatNitrox { get; set; }    
        [JsonPropertyName("sslnumcardsupsecondary")]public string SslNumberOfCardsUpSecondary { get; set; }    
        public string Sslcardssecondary { get; set; }    
        public string Sslnumcardsup { get; set; }    
        public string Sslcardstatus { get; set; }    
        public string Sslcards { get; set; }    
        public string Sslenginestatus { get; set; }    
        public string Ssltotsessions { get; set; }    
        public double? Sslsessionsrate { get; set; }    
        public string Ssltottransactions { get; set; }    
        public double? Ssltransactionsrate { get; set; }    
        public string SsltotSslv2transactions { get; set; }    
        public double? SslSslv2transactionsrate { get; set; }    
        public string SsltotSslv3transactions { get; set; }    
        public double? SslSslv3transactionsrate { get; set; }    
        public string Ssltottlsv1transactions { get; set; }    
        public double? Ssltlsv1transactionsrate { get; set; }    
        public string Ssltottlsv11transactions { get; set; }    
        public double? Ssltlsv11transactionsrate { get; set; }    
        public string Ssltottlsv12transactions { get; set; }    
        public double? Ssltlsv12transactionsrate { get; set; }    
        public string Ssltottlsv13transactions { get; set; }    
        public double? Ssltlsv13transactionsrate { get; set; }    
        public string Ssltotdtlsv1transactions { get; set; }    
        public double? Ssldtlsv1transactionsrate { get; set; }    
        public string Ssltotdtlsv12transactions { get; set; }    
        public double? Ssldtlsv12transactionsrate { get; set; }    
        public string SsltotSslv2sessions { get; set; }    
        public double? SslSslv2sessionsrate { get; set; }    
        public string SsltotSslv3sessions { get; set; }    
        public double? SslSslv3sessionsrate { get; set; }    
        public string Ssltottlsv1sessions { get; set; }    
        public double? Ssltlsv1sessionsrate { get; set; }    
        public string Ssltottlsv11sessions { get; set; }    
        public double? Ssltlsv11sessionsrate { get; set; }    
        public string Ssltottlsv12sessions { get; set; }    
        public double? Ssltlsv12sessionsrate { get; set; }    
        public string Ssltottlsv13sessions { get; set; }    
        public double? Ssltlsv13sessionsrate { get; set; }    
        public string Ssltotdtlsv1sessions { get; set; }    
        public double? Ssldtlsv1sessionsrate { get; set; }    
        public string Ssltotdtlsv12sessions { get; set; }    
        public double? Ssldtlsv12sessionsrate { get; set; }    
        public string Ssltotnewsessions { get; set; }    
        public double? Sslnewsessionsrate { get; set; }    
        public string Ssltotsessionmiss { get; set; }    
        public double? Sslsessionmissrate { get; set; }    
        public string Ssltotsessionhits { get; set; }    
        public double? Sslsessionhitsrate { get; set; }    
        public string Sslbetotsessions { get; set; }    
        public double? Sslbesessionsrate { get; set; }     
        public string SslbetotSslv3sessions { get; set; }    
        public double? SslbeSslv3sessionsrate { get; set; }    
        public string Sslbetottlsv1sessions { get; set; }    
        public double? Sslbetlsv1sessionsrate { get; set; }    
        public string Sslbetottlsv11sessions { get; set; }    
        public double? Sslbetlsv11sessionsrate { get; set; }    
        public string Sslbetottlsv12sessions { get; set; }    
        public double? Sslbetlsv12sessionsrate { get; set; }    
        public string Sslbetotdtlsv1sessions { get; set; }    
        public double? Sslbedtlsv1sessionsrate { get; set; }    
        public string Sslbetotsessionmultiplexattempts { get; set; }    
        public double? Sslbesessionmultiplexattemptsrate { get; set; }    
        public string Sslbetotsessionmultiplexattemptsuccess { get; set; }    
        public double? Sslbesessionmultiplexattemptsuccessrate { get; set; }    
        public string Sslbetotsessionmultiplexattemptfails { get; set; }    
        public double? Sslbesessionmultiplexattemptfailsrate { get; set; }    
        public string Ssltotenc { get; set; }    
        public double? Sslencrate { get; set; }    
        public string Ssltotdec { get; set; }    
        public double? Ssldecrate { get; set; }    
        public string SsltotSslserverinrecords { get; set; }    
        public double? SslSslserverinrecordsrate { get; set; }    
        public string Ssltotrenegsessions { get; set; }    
        public double? Sslrenegsessionsrate { get; set; }    
        public string SsltotSslv3renegsessions { get; set; }    
        public double? SslSslv3renegsessionsrate { get; set; }    
        public string Ssltottlsv1renegsessions { get; set; }    
        public double? Ssltlsv1renegsessionsrate { get; set; }    
        public string Ssltottlsv11renegsessions { get; set; }    
        public double? Ssltlsv11renegsessionsrate { get; set; }    
        public string Ssltottlsv12renegsessions { get; set; }    
        public double? Ssltlsv12renegsessionsrate { get; set; }    
        public string Ssltotdtlsv1renegsessions { get; set; }    
        public double? Ssldtlsv1renegsessionsrate { get; set; }    
        public string Ssltotdtlsv12renegsessions { get; set; }    
        public double? Ssldtlsv12renegsessionsrate { get; set; }    
        public string Ssltotrsa512keyexchanges { get; set; }    
        public double? Sslrsa512keyexchangesrate { get; set; }    
        public string Ssltotrsa1024keyexchanges { get; set; }    
        public double? Sslrsa1024keyexchangesrate { get; set; }    
        public string Ssltotrsa2048keyexchanges { get; set; }    
        public double? Sslrsa2048keyexchangesrate { get; set; }    
        public string Ssltotrsa3072keyexchanges { get; set; }    
        public double? Sslrsa3072keyexchangesrate { get; set; }    
        public string Ssltotrsa4096keyexchanges { get; set; }    
        public double? Sslrsa4096keyexchangesrate { get; set; }    
        public string Ssltotdh512keyexchanges { get; set; }    
        public double? Ssldh512keyexchangesrate { get; set; }    
        public string Ssltotdh1024keyexchanges { get; set; }    
        public double? Ssldh1024keyexchangesrate { get; set; }    
        public string Ssltotdh2048keyexchanges { get; set; }    
        public double? Ssldh2048keyexchangesrate { get; set; }    
        public string Ssltotdh4096keyexchanges { get; set; }    
        public double? Ssldh4096keyexchangesrate { get; set; }    
        public string Ssltotecdhe521keyexchanges { get; set; }    
        public double? Sslecdhe521keyexchangesrate { get; set; }    
        public string Ssltotecdhe384keyexchanges { get; set; }    
        public double? Sslecdhe384keyexchangesrate { get; set; }    
        public string Ssltotecdhe256keyexchanges { get; set; }    
        public double? Sslecdhe256keyexchangesrate { get; set; }    
        public string Ssltotecdhe224keyexchanges { get; set; }    
        public double? Sslecdhe224keyexchangesrate { get; set; }    
        public string Ssltotecdhetransactions { get; set; }    
        public double? Sslecdhetransactionsrate { get; set; }    
        public string Ssltot40bitrc4ciphers { get; set; }    
        public double? Ssl40bitrc4ciphersrate { get; set; }    
        public string Ssltot56bitrc4ciphers { get; set; }    
        public double? Ssl56bitrc4ciphersrate { get; set; }    
        public string Ssltot64bitrc4ciphers { get; set; }    
        public double? Ssl64bitrc4ciphersrate { get; set; }    
        public string Ssltot128bitrc4ciphers { get; set; }    
        public double? Ssl128bitrc4ciphersrate { get; set; }    
        public string Ssltot40bitdesciphers { get; set; }    
        public double? Ssl40bitdesciphersrate { get; set; }    
        public string Ssltot56bitdesciphers { get; set; }    
        public double? Ssl56bitdesciphersrate { get; set; }    
        public string Ssltot168bit3desciphers { get; set; }    
        public double? Ssl168bit3desciphersrate { get; set; }    
        public string Ssltotcipheraes128 { get; set; }    
        public double? Sslcipheraes128rate { get; set; }    
        public string Ssltotcipheraes256 { get; set; }    
        public double? Sslcipheraes256rate { get; set; }    
        public string Ssltot40bitrc2ciphers { get; set; }    
        public double? Ssl40bitrc2ciphersrate { get; set; }    
        public string Ssltot56bitrc2ciphers { get; set; }    
        public double? Ssl56bitrc2ciphersrate { get; set; }    
        public string Ssltot128bitrc2ciphers { get; set; }    
        public double? Ssl128bitrc2ciphersrate { get; set; }    
        public string Ssltot128bitaesgcmciphers { get; set; }    
        public double? Ssl128bitaesgcmciphersrate { get; set; }    
        public string Ssltot256bitaesgcmciphers { get; set; }    
        public double? Ssl256bitaesgcmciphersrate { get; set; }    
        public string Ssltotnullciphers { get; set; }    
        public double? Sslnullciphersrate { get; set; }    
        public string Ssltotmd5mac { get; set; }    
        public double? Sslmd5macrate { get; set; }    
        public string Ssltotshamac { get; set; }    
        public double? Sslshamacrate { get; set; }    
        public string Ssltotsha256mac { get; set; }    
        public double? Sslsha256macrate { get; set; }    
        public string Ssltotsha384mac { get; set; }    
        public double? Sslsha384macrate { get; set; }    
        public string SsltotSslv2handshakes { get; set; }    
        public double? SslSslv2handshakesrate { get; set; }    
        public string SsltotSslv3handshakes { get; set; }    
        public double? SslSslv3handshakesrate { get; set; }    
        public string Ssltottlsv1handshakes { get; set; }    
        public double? Ssltlsv1handshakesrate { get; set; }    
        public string Ssltottlsv11handshakes { get; set; }    
        public double? Ssltlsv11handshakesrate { get; set; }    
        public string Ssltottlsv12handshakes { get; set; }    
        public double? Ssltlsv12handshakesrate { get; set; }    
        public string Ssltottlsv13handshakes { get; set; }    
        public double? Ssltlsv13handshakesrate { get; set; }    
        public string Ssltotdtlsv1handshakes { get; set; }    
        public double? Ssldtlsv1handshakesrate { get; set; }    
        public string Ssltotdtlsv12handshakes { get; set; }    
        public double? Ssldtlsv12handshakesrate { get; set; }    
        public string SsltotSslv2clientauthentications { get; set; }    
        public double? SslSslv2clientauthenticationsrate { get; set; }    
        public string SsltotSslv3clientauthentications { get; set; }    
        public double? SslSslv3clientauthenticationsrate { get; set; }    
        public string Ssltottlsv1clientauthentications { get; set; }    
        public double? Ssltlsv1clientauthenticationsrate { get; set; }    
        public string Ssltottlsv11clientauthentications { get; set; }    
        public double? Ssltlsv11clientauthenticationsrate { get; set; }    
        public string Ssltottlsv12clientauthentications { get; set; }    
        public double? Ssltlsv12clientauthenticationsrate { get; set; }    
        public string Ssltottlsv13clientauthentications { get; set; }    
        public double? Ssltlsv13clientauthenticationsrate { get; set; }    
        public string Ssltotdtlsv1clientauthentications { get; set; }    
        public double? Ssldtlsv1clientauthenticationsrate { get; set; }    
        public string Ssltotdtlsv12clientauthentications { get; set; }    
        public double? Ssldtlsv12clientauthenticationsrate { get; set; }        
        public string Ssltotrsaauthorizations { get; set; }    
        public double? Sslrsaauthorizationsrate { get; set; }    
        public string Ssltotdhauthorizations { get; set; }    
        public double? Ssldhauthorizationsrate { get; set; }    
        public string Ssltotdssauthorizations { get; set; }    
        public double? Ssldssauthorizationsrate { get; set; }    
        public string Ssltotecdsaauthorizations { get; set; }    
        public double? Sslecdsaauthorizationsrate { get; set; }    
        public string Ssltotnullauthorizations { get; set; }    
        public double? Sslnullauthorizationsrate { get; set; }    
        public string Ssltotbkendsessionrenegotiate { get; set; }    
        public double? Sslbkendsessionrenegotiaterate { get; set; }    
        public string SsltotbkendSslv3renego { get; set; }    
        public double? SslbkendSslv3renegorate { get; set; }    
        public string Ssltotbkendtlsvlrenego { get; set; }    
        public double? Sslbkendtlsvlrenegorate { get; set; }    
        public string Ssltotbkendtlsv11renego { get; set; }    
        public double? Sslbkendtlsv11renegorate { get; set; }    
        public string Ssltotbkendtlsv12renego { get; set; }    
        public double? Sslbkendtlsv12renegorate { get; set; }    
        public string Ssltotbkenddtlsvlrenego { get; set; }    
        public double? Sslbkenddtlsvlrenegorate { get; set; }    
        public string Sslbetotrsa512keyexchanges { get; set; }    
        public double? Sslbersa512keyexchangesrate { get; set; }    
        public string Sslbetotrsa1024keyexchanges { get; set; }    
        public double? Sslbersa1024keyexchangesrate { get; set; }    
        public string Sslbetotrsa2048keyexchanges { get; set; }    
        public double? Sslbersa2048keyexchangesrate { get; set; }    
        public string Sslbetotrsa3072keyexchanges { get; set; }    
        public double? Sslbersa3072keyexchangesrate { get; set; }    
        public string Sslbetotrsa4096keyexchanges { get; set; }    
        public double? Sslbersa4096keyexchangesrate { get; set; }    
        public string Sslbetotdh512keyexchanges { get; set; }    
        public double? Sslbedh512keyexchangesrate { get; set; }    
        public string Sslbetotdh1024keyexchanges { get; set; }    
        public double? Sslbedh1024keyexchangesrate { get; set; }    
        public string Sslbetotdh2048keyexchanges { get; set; }    
        public double? Sslbedh2048keyexchangesrate { get; set; }    
        public string Sslbetotdh4096keyexchanges { get; set; }    
        public double? Sslbedh4096keyexchangesrate { get; set; }    
        public string Sslbetotecdhecurve521 { get; set; }    
        public double? Sslbeecdhecurve521rate { get; set; }    
        public string Sslbetotecdhecurve384 { get; set; }    
        public double? Sslbeecdhecurve384rate { get; set; }    
        public string Sslbetotecdhecurve256 { get; set; }    
        public double? Sslbeecdhecurve256rate { get; set; }    
        public string Sslbetotecdhecurve224 { get; set; }    
        public double? Sslbeecdhecurve224rate { get; set; }    
        public string Sslbetot40bitrc4ciphers { get; set; }    
        public double? Sslbe40bitrc4ciphersrate { get; set; }    
        public string Sslbetot56bitrc4ciphers { get; set; }    
        public double? Sslbe56bitrc4ciphersrate { get; set; }    
        public string Sslbetot64bitrc4ciphers { get; set; }    
        public double? Sslbe64bitrc4ciphersrate { get; set; }    
        public string Sslbetot128bitrc4ciphers { get; set; }    
        public double? Sslbe128bitrc4ciphersrate { get; set; }    
        public string Sslbetot40bitdesciphers { get; set; }    
        public double? Sslbe40bitdesciphersrate { get; set; }    
        public string Sslbetot56bitdesciphers { get; set; }    
        public double? Sslbe56bitdesciphersrate { get; set; }    
        public string Sslbetot168bit3desciphers { get; set; }    
        public double? Sslbe168bit3desciphersrate { get; set; }    
        public string Ssltotbkendcipheraes128 { get; set; }    
        public double? Sslbkendcipheraes128rate { get; set; }    
        public string Ssltotbkendcipheraes256 { get; set; }    
        public double? Sslbkendcipheraes256rate { get; set; }    
        public string Sslbetot40bitrc2ciphers { get; set; }    
        public double? Sslbe40bitrc2ciphersrate { get; set; }    
        public string Sslbetot56bitrc2ciphers { get; set; }    
        public double? Sslbe56bitrc2ciphersrate { get; set; }    
        public string Sslbetot128bitrc2ciphers { get; set; }    
        public double? Sslbe128bitrc2ciphersrate { get; set; }    
        public string Ssltotbkendcipheraesgcm128 { get; set; }    
        public double? Sslbkendcipheraesgcm128rate { get; set; }    
        public string Ssltotbkendcipheraesgcm256 { get; set; }    
        public double? Sslbkendcipheraesgcm256rate { get; set; }    
        public string Sslbetotnullciphers { get; set; }    
        public double? Sslbenullciphersrate { get; set; }    
        public string Sslbetotmd5mac { get; set; }    
        public double? Sslbemd5macrate { get; set; }    
        public string Sslbetotshamac { get; set; }    
        public double? Sslbeshamacrate { get; set; }    
        public string Sslbetotsha256mac { get; set; }    
        public double? Sslbesha256macrate { get; set; }    
        public string Sslbetotsha384mac { get; set; }    
        public double? Sslbesha384macrate { get; set; }    
        public string SslbetotSslv3handshakes { get; set; }    
        public double? SslbeSslv3handshakesrate { get; set; }    
        public string Sslbetottlsv1handshakes { get; set; }    
        public double? Sslbetlsv1handshakesrate { get; set; }    
        public string Sslbetottlsv11handshakes { get; set; }    
        public double? Sslbetlsv11handshakesrate { get; set; }    
        public string Sslbetottlsv12handshakes { get; set; }    
        public double? Sslbetlsv12handshakesrate { get; set; }    
        public string Sslbetotdtlsv1handshakes { get; set; }    
        public double? Sslbedtlsv1handshakesrate { get; set; }    
        public string SslbetotSslv3clientauthentications { get; set; }    
        public double? SslbeSslv3clientauthenticationsrate { get; set; }    
        public string Sslbetottlsv1clientauthentications { get; set; }    
        public double? Sslbetlsv1clientauthenticationsrate { get; set; }    
        public string Sslbetottlsv11clientauthentications { get; set; }    
        public double? Sslbetlsv11clientauthenticationsrate { get; set; }    
        public string Sslbetottlsv12clientauthentications { get; set; }    
        public double? Sslbetlsv12clientauthenticationsrate { get; set; }    
        public string Sslbetotdtlsv1clientauthentications { get; set; }    
        public double? Sslbedtlsv1clientauthenticationsrate { get; set; }    
        public string Sslbetotrsaauthorizations { get; set; }    
        public double? Sslbersaauthorizationsrate { get; set; }    
        public string Sslbetotdhauthorizations { get; set; }    
        public double? Sslbedhauthorizationsrate { get; set; }    
        public string Sslbetotdssauthorizations { get; set; }    
        public double? Sslbedssauthorizationsrate { get; set; }    
        public string Sslbetotecdsaauthorizations { get; set; }    
        public double? Sslbeecdsaauthorizationsrate { get; set; }    
        public string Sslbetotnullauthorizations { get; set; }    
        public double? Sslbenullauthorizationsrate { get; set; }    
        public string Ssltotoffloadrsakeyexchanges { get; set; }    
        public double? Ssloffloadrsakeyexchangesrate { get; set; }    
        public string Ssltotoffloadsignrsa { get; set; }    
        public double? Ssloffloadsignrsarate { get; set; }    
        public string Ssltotoffloaddhkeyexchanges { get; set; }    
        public double? Ssloffloaddhkeyexchangesrate { get; set; }    
        public string Ssltotoffloadbulkrc4 { get; set; }    
        public double? Ssloffloadbulkrc4rate { get; set; }    
        public string Ssltotoffloadbulkdes { get; set; }    
        public double? Ssloffloadbulkdesrate { get; set; }    
        public string Ssltotoffloadbulkaes { get; set; }    
        public double? Ssloffloadbulkaesrate { get; set; }    
        public string Ssltotoffloadbulkaesgcm128 { get; set; }    
        public double? Ssloffloadbulkaesgcm128rate { get; set; }    
        public string Ssltotoffloadbulkaesgcm256 { get; set; }    
        public double? Ssloffloadbulkaesgcm256rate { get; set; }    
        public string Ssltotenchw { get; set; }    
        public double? Sslenchwrate { get; set; }    
        public string Ssltotencsw { get; set; }    
        public double? Sslencswrate { get; set; }    
        public string Ssltotencfe { get; set; }    
        public double? Sslencferate { get; set; }    
        public string Ssltothwencfe { get; set; }    
        public double? Sslhwencferate { get; set; }    
        public string Ssltotswencfe { get; set; }    
        public double? Sslswencferate { get; set; }    
        public string Ssltotencbe { get; set; }    
        public double? Sslencberate { get; set; }    
        public string Ssltothwencbe { get; set; }    
        public double? Sslhwencberate { get; set; }    
        public string Ssltotswencbe { get; set; }    
        public double? Sslswencberate { get; set; }    
        public string Ssltotdechw { get; set; }    
        public double? Ssldechwrate { get; set; }    
        public string Ssltotdecsw { get; set; }    
        public double? Ssldecswrate { get; set; }    
        public string Ssltotdecfe { get; set; }    
        public double? Ssldecferate { get; set; }    
        public string Ssltothwdecfe { get; set; }    
        public double? Sslhwdecferate { get; set; }    
        public string Ssltotswdecfe { get; set; }    
        public double? Sslswdecferate { get; set; }    
        public string Ssltotdecbe { get; set; }    
        public double? Ssldecberate { get; set; }    
        public string Ssltothwdecbe { get; set; }    
        public double? Sslhwdecberate { get; set; }    
        public string Ssltotswdecbe { get; set; }    
        public double? Sslswdecberate { get; set; }    
        public string SslcurSslinfospcbinusecount { get; set; }    
        public double? SslcurSslinfospcbinusecountrate { get; set; }    
        public string Sslcursessions { get; set; }    
        public double? Sslcursessionsrate { get; set; }    
        public string Sslcurqsize { get; set; }    
        public double? Sslcurqsizerate { get; set; }    
        public string SslcurSslinfonscardinqcount { get; set; }    
        public double? SslcurSslinfonscardinqcountrate { get; set; }    
        public string SslcurSslinfocardinblkq { get; set; }    
        public double? SslcurSslinfocardinblkqrate { get; set; }    
        public string SslcurSslinfocardinkeyq { get; set; }    
        public double? SslcurSslinfocardinkeyqrate { get; set; }    
        public string Sslbemaxmultiplexedsessions { get; set; }    
        public double? Sslbemaxmultiplexedsessionsrate { get; set; }    
        public string Ssltot128bitideaciphers { get; set; }    
        public double? Ssl128bitideaciphersrate { get; set; }    
        public string Sslbetot128bitideaciphers { get; set; }    
        public double? Sslbe128bitideaciphersrate { get; set; }
    }
}