using System.Text.Json.Serialization;

namespace CoreLayer.Citrix.Adc.NitroData.Api.Statistics.Ssl
{
    public class SslStats
    {
        [JsonPropertyName("ssltothwdecbesecondary")]public string SslTotalHardwareBytesDecryptedBackEndSecondary { get; set; }    
        [JsonPropertyName("sslhwdecbesecondaryrate")]public double? SslHardwareBytesDecryptedBackEndSecondaryRate { get; set; }    
        [JsonPropertyName("ssltothwdecfesecondary")]public string SslTotalHardwareBytesDecryptedFrontEndSecondary { get; set; }    
        [JsonPropertyName("sslhwdecfesecondaryrate")]public double? SslHardwareBytesDecryptedFrontEndSecondaryRate { get; set; }    
        [JsonPropertyName("ssltothwencbesecondary")]public string SslTotalHardwareBytesEncryptedBackEndSecondary { get; set; }    
        [JsonPropertyName("sslhwencbesecondaryrate")]public double? SslHardwareBytesEncryptedBackEndSecondaryRate { get; set; }    
        [JsonPropertyName("ssltothwencfesecondary")]public string SslTotalHardwareBytesEncryptedFrontEndSecondary { get; set; }    
        [JsonPropertyName("sslhwencfesecondaryrate")]public double? SslHardwareBytesEncryptedFrontEndSecondaryRate { get; set; }    
        [JsonPropertyName("ssltotdechwsecondary")]public string SslTotalBytesDecryptedHardwareSecondary { get; set; }    
        [JsonPropertyName("ssldechwsecondaryrate")]public double? SslBytesDecryptedHardwareSecondaryRate { get; set; }    
        [JsonPropertyName("ssltotenchwsecondary")]public string SslTotalBytesEncryptedHardwareSecondary { get; set; }    
        [JsonPropertyName("sslenchwsecondaryrate")]public double? SslBytesEncryptedHardwareSecondaryRate { get; set; }    
        [JsonPropertyName("sslcryptoutilizationsymmstat")]public string SslCryptoUtilizationSymmetricStat { get; set; }    
        [JsonPropertyName("sslcryptoutilizationasymstat")]public string SslCryptoUtilizationAsymmetricStat { get; set; }    
        [JsonPropertyName("sslcryptoutilizationstat2nd")]public double? SslCryptoUtilizationStat { get; set; }    
        [JsonPropertyName("sslcryptoutilizationstat")]public double? SslCryptoUtilizationStatNitrox { get; set; }    
        [JsonPropertyName("sslnumcardsupsecondary")]public string SslNumberOfCardsUpSecondary { get; set; }    
        public string SslCardsSecondary { get; set; }    
        [JsonPropertyName("sslnumcardsup")]public string SslNumberOfCardsUp { get; set; }    
        public string SslCardStatus { get; set; }    
        public string SslCards { get; set; }    
        public string SslEngineStatus { get; set; }    
        [JsonPropertyName("ssltotsessions")]public string SslTotalSessions { get; set; }    
        public double? SslSessionsRate { get; set; }    
        [JsonPropertyName("ssltottransactions")]public string SslTotalTransactions { get; set; }    
        public double? SslTransactionsRate { get; set; }    
        [JsonPropertyName("ssltotsslv2transactions")]public string SslTotalSslV2Transactions { get; set; }    
        public double? SslSslV2TransactionsRate { get; set; }    
        [JsonPropertyName("ssltotsslv3transactions")]public string SslTotalSslV3Transactions { get; set; }    
        public double? SslSslV3TransactionsRate { get; set; }    
        [JsonPropertyName("ssltottlsv1transactions")]public string SslTotalTlsV1Transactions { get; set; }    
        public double? SslTlsV1TransactionsRate { get; set; }    
        [JsonPropertyName("ssltottlsv11transactions")]public string SslTotalTlsV11Transactions { get; set; }    
        public double? SslTlsV11TransactionsRate { get; set; }    
        [JsonPropertyName("ssltottlsv12transactions")]public string SslTotalTlsV12Transactions { get; set; }    
        public double? SslTlsV12TransactionsRate { get; set; }    
        [JsonPropertyName("ssltottlsv13transactions")]public string SslTotalTlsV13Transactions { get; set; }    
        public double? SslTlsV13TransactionsRate { get; set; }    
        [JsonPropertyName("ssltotdtlsv1transactions")]public string SslTotalDtlsV1Transactions { get; set; }    
        public double? SslDtlsV1TransactionsRate { get; set; }    
        [JsonPropertyName("ssltotdtlsv12transactions")]public string SslTotalDtlsV12Transactions { get; set; }    
        public double? SslDtlsV12TransactionsRate { get; set; }    
        [JsonPropertyName("ssltotsslv2sessions")]public string SslTotalSslV2Sessions { get; set; }    
        public double? SslSslV2SessionsRate { get; set; }    
        [JsonPropertyName("ssltotsslv3sessions")]public string SslTotalSslV3Sessions { get; set; }    
        public double? SslSslV3SessionsRate { get; set; }    
        [JsonPropertyName("ssltottlsv1sessions")]public string SslTotalTlsV1Sessions { get; set; }    
        public double? SslTlsV1SessionsRate { get; set; }    
        [JsonPropertyName("ssltottlsv11sessions")]public string SslTotalTlsV11Sessions { get; set; }    
        public double? SslTlsV11SessionsRate { get; set; }    
        [JsonPropertyName("ssltottlsv12sessions")]public string SslTotalTlsV12Sessions { get; set; }    
        public double? SslTlsV12SessionsRate { get; set; }    
        [JsonPropertyName("ssltottlsv13sessions")]public string SslTotalTlsV13Sessions { get; set; }    
        public double? SslTlsV13SessionsRate { get; set; }    
        [JsonPropertyName("ssltotdtlsv1sessions")]public string SslTotalDtlsV1Sessions { get; set; }    
        public double? SslDtlsV1SessionsRate { get; set; }    
        [JsonPropertyName("ssltotdtlsv12sessions")]public string SslTotalDtlsV12Sessions { get; set; }    
        public double? SslDtlsV12SessionsRate { get; set; }    
        [JsonPropertyName("ssltotnewsessions")]public string SslTotalNewSessions { get; set; }    
        public double? SslNewSessionsRate { get; set; }    
        [JsonPropertyName("ssltotsessionmiss")]public string SslTotalSessionMisses { get; set; }    
        [JsonPropertyName("sslsessionmissrate")]public double? SslSessionMissesRate { get; set; }    
        [JsonPropertyName("ssltotsessionhits")]public string SslTotalSessionHits { get; set; }    
        public double? SslSessionHitsRate { get; set; }    
        [JsonPropertyName("sslbetotsessions")]public string SslBackendTotalSessions { get; set; }    
        [JsonPropertyName("sslbesessionsrate")]public double? SslBackendSessionsRate { get; set; }     
        [JsonPropertyName("sslbetotsslv3sessions")]public string SslBackendTotalSslV3Sessions { get; set; }    
        [JsonPropertyName("sslbesslv3sessionsrate")]public double? SslBackendSslV3SessionsRate { get; set; }    
        [JsonPropertyName("sslbetottlsv1sessions")]public string SslBackendTotalTlsV1Sessions { get; set; }    
        [JsonPropertyName("sslbetlsv1sessionsrate")]public double? SslBackendTlsV1SessionsRate { get; set; }    
        [JsonPropertyName("sslbetottlsv11sessions")]public string SslBackendTotalTlsV11Sessions { get; set; }    
        [JsonPropertyName("sslbetlsv11sessionsrate")]public double? SslBackendTlsV11SessionsRate { get; set; }    
        [JsonPropertyName("sslbetottlsv12sessions")]public string SslBackendTotalTlsV12Sessions { get; set; }    
        [JsonPropertyName("sslbetlsv12sessionsrate")]public double? SslBackendTlsV12SessionsRate { get; set; }    
        [JsonPropertyName("sslbetotdtlsv1sessions")]public string SslBackendTotalDtlsV1Sessions { get; set; }    
        [JsonPropertyName("sslbedtlsv1sessionsrate")]public double? SslBackendDtlsV1SessionsRate { get; set; }    
        [JsonPropertyName("sslbetotsessionmultiplexattempts")]public string SslBackendTotalSessionMultiplexAttempts { get; set; }    
        [JsonPropertyName("sslbesessionmultiplexattemptsrate")]public double? SslBackendSessionMultiplexAttemptsRate { get; set; }    
        [JsonPropertyName("sslbetotsessionmultiplexattemptsucces")]public string SslBackendTotalSessionMultiplexAttemptSuccess { get; set; }    
        [JsonPropertyName("sslbesessionmultiplexattemptsuccesrate")]public double? SslBackendSessionMultiplexAttemptSuccessRate { get; set; }    
        [JsonPropertyName("sslbetotsessionmultiplexattemptfails")]public string SslBackendTotalSessionMultiplexAttemptFails { get; set; }    
        [JsonPropertyName("sslbesessionmultiplexattemptfailsrate")]public double? SslBackendSessionMultiplexAttemptFailsRate { get; set; }    
        [JsonPropertyName("ssltotenc")]public string SslTotalEncryptedBytes { get; set; }    
        [JsonPropertyName("sslencrate")]public double? SslEncryptedBytesRate { get; set; }    
        [JsonPropertyName("ssltotdec")]public string SslTotalDecryptedBytes { get; set; }    
        [JsonPropertyName("ssldecrate")]public double? SslDecryptedBytesRate { get; set; }    
        [JsonPropertyName("ssltotsslserverinrecords")]public string SslTotalSslServerInRecords { get; set; }    
        public double? SslSslServerInRecordsRate { get; set; }    
        [JsonPropertyName("ssltotrenegsessions")]public string SslTotalRenegotiatedSessions { get; set; }    
        [JsonPropertyName("sslrenegsessionsrate")]public double? SslRenegotiatedSessionsRate { get; set; }    
        [JsonPropertyName("ssltotsslv3renegsessions")]public string SslTotalSslV3RenegotiatedSessions { get; set; }    
        [JsonPropertyName("sslsslv3renegsessionsrate")]public double? SslSslV3RenegotiatedSessionsRate { get; set; }    
        [JsonPropertyName("ssltottlsv1renegsessions")]public string SslTotalTlsV1RenegotiatedSessions { get; set; }    
        [JsonPropertyName("ssltlsv1renegsessionsrate")]public double? SslTlsV1RenegotiatedSessionsRate { get; set; }    
        [JsonPropertyName("ssltottlsv11renegsessions")]public string SslTotalTlsV11RenegotiatedSessions { get; set; }    
        [JsonPropertyName("ssltlsv11renegsessionsrate")]public double? SslTlsV11RenegotiatedSessionsRate { get; set; }    
        [JsonPropertyName("ssltottlsv12renegsessions")]public string SslTotalTlsV12RenegotiatedSessions { get; set; }    
        [JsonPropertyName("ssltlsv12renegsessionsrate")]public double? SslTlsV12RenegotiatedSessionsRate { get; set; }    
        [JsonPropertyName("ssltotdtlsv1renegsessions")]public string SslTotalDtlsV1RenegotiatedSessions { get; set; }    
        [JsonPropertyName("ssldtlsv1renegsessionsrate")]public double? SslDtlsV1RenegotiatedSessionsRate { get; set; }    
        [JsonPropertyName("ssltotdtlsv12renegsessions")]public string SslTotalDtlsV12RenegotiatedSessions { get; set; }    
        [JsonPropertyName("ssldtlsv12renegsessionsrate")]public double? SslDtlsV12RenegotiatedSessionsRate { get; set; }    
        [JsonPropertyName("ssltotrsa512keyexchanges")]public string SslTotalRsa512KeyExchanges { get; set; }    
        public double? SslRsa512KeyExchangesRate { get; set; }    
        [JsonPropertyName("ssltotrsa1024keyexchanges")]public string SslTotalRsa1024KeyExchanges { get; set; }    
        public double? SslRsa1024KeyExchangesRate { get; set; }    
        [JsonPropertyName("ssltotrsa2048keyexchanges")]public string SslTotalRsa2048KeyExchanges { get; set; }    
        public double? SslRsa2048KeyExchangesRate { get; set; }    
        [JsonPropertyName("ssltotrsa3072keyexchanges")]public string SslTotalRsa3072KeyExchanges { get; set; }    
        public double? SslRsa3072KeyExchangesRate { get; set; }    
        [JsonPropertyName("ssltotrsa4096keyexchanges")]public string SslTotalRsa4096KeyExchanges { get; set; }    
        public double? SslRsa4096KeyExchangesRate { get; set; }    
        [JsonPropertyName("ssltotdh512keyexchanges")]public string SslTotalDh512KeyExchanges { get; set; }    
        public double? SslDh512KeyExchangesRate { get; set; }    
        [JsonPropertyName("ssltotdh1024keyexchanges")]public string SslTotalDh1024KeyExchanges { get; set; }    
        public double? SslDh1024KeyExchangesRate { get; set; }    
        [JsonPropertyName("ssltotdh2048keyexchanges")]public string SslTotalDh2048KeyExchanges { get; set; }    
        public double? SslDh2048KeyExchangesRate { get; set; }    
        [JsonPropertyName("ssltotdh4096keyexchanges")]public string SslTotalDh4096KeyExchanges { get; set; }    
        public double? SslDh4096KeyExchangesRate { get; set; }    
        [JsonPropertyName("ssltotecdhe521keyexchanges")]public string SslTotalEcdhe521KeyExchanges { get; set; }    
        public double? SslEcdhe521KeyExchangesRate { get; set; }    
        [JsonPropertyName("ssltotecdhe384keyexchanges")]public string SslTotalEcdhe384KeyExchanges { get; set; }    
        public double? SslEcdhe384KeyExchangesRate { get; set; }    
        [JsonPropertyName("ssltotecdhe256keyexchanges")]public string SslTotalEcdhe256KeyExchanges { get; set; }    
        public double? SslEcdhe256KeyExchangesRate { get; set; }    
        [JsonPropertyName("ssltotecdhe224keyexchanges")]public string SslTotalEcdhe224KeyExchanges { get; set; }    
        public double? SslEcdhe224KeyExchangesRate { get; set; }    
        [JsonPropertyName("ssltotecdhetransactions")]public string SslTotalEcdheTransactions { get; set; }    
        public double? SslEcdheTransactionsRate { get; set; }    
        [JsonPropertyName("ssltot40bitrc4ciphers")]public string SslTotal40BitRc4Ciphers { get; set; }    
        public double? Ssl40BitRc4CiphersRate { get; set; }    
        [JsonPropertyName("ssltot56bitrc4ciphers")]public string SslTotal56BitRc4Ciphers { get; set; }    
        public double? Ssl56BitRc4CiphersRate { get; set; }    
        [JsonPropertyName("ssltot64bitrc4ciphers")]public string SslTotal64BitRc4Ciphers { get; set; }    
        public double? Ssl64BitRc4CiphersRate { get; set; }    
        [JsonPropertyName("ssltot128bitrc4ciphers")]public string SslTotal128BitRc4Ciphers { get; set; }    
        public double? Ssl128BitRc4CiphersRate { get; set; }    
        [JsonPropertyName("ssltot40bitdesciphers")]public string SslTotal40BitDesCiphers { get; set; }    
        public double? Ssl40BitDesCiphersRate { get; set; }    
        [JsonPropertyName("ssltot56bitdesciphers")]public string SslTotal56BitDesCiphers { get; set; }    
        public double? Ssl56BitDesCiphersRate { get; set; }    
        [JsonPropertyName("ssltot168bit3desciphers")]public string SslTotal168Bit3DesCiphers { get; set; }    
        public double? Ssl168Bit3DesCiphersRate { get; set; }    
        [JsonPropertyName("ssltotcipheraes128")]public string SslTotalCipherAes128 { get; set; }    
        public double? SslCipherAes128Rate { get; set; }    
        [JsonPropertyName("ssltotcipheraes256")]public string SslTotalCipherAes256 { get; set; }    
        public double? SslCipherAes256Rate { get; set; }    
        [JsonPropertyName("ssltot40bitrc2ciphers")]public string SslTotal40BitRc2Ciphers { get; set; }    
        public double? Ssl40BitRc2CiphersRate { get; set; }    
        [JsonPropertyName("ssltot56bitrc2ciphers")]public string SslTotal56BitRc2Ciphers { get; set; }    
        public double? Ssl56BitRc2CiphersRate { get; set; }    
        [JsonPropertyName("ssltot128bitrc2ciphers")]public string SslTotal128BitRc2Ciphers { get; set; }    
        public double? Ssl128BitRc2CiphersRate { get; set; }    
        [JsonPropertyName("ssltot128bitaesgcmciphers")]public string SslTotal128BitAesGcmCiphers { get; set; }    
        public double? Ssl128BitAesGcmCiphersRate { get; set; }    
        [JsonPropertyName("ssltot256bitaesgcmciphers")]public string SslTotal256BitAesGcmCiphers { get; set; }    
        public double? Ssl256BitAesGcmCiphersRate { get; set; }    
        [JsonPropertyName("ssltotnullciphers")]public string SslTotalNullCiphers { get; set; }    
        public double? SslNullCiphersRate { get; set; }    
        [JsonPropertyName("ssltotmd5mac")]public string SslTotalMd5Mac { get; set; }    
        public double? SslMd5MacRate { get; set; }    
        [JsonPropertyName("ssltotshamac")]public string SslTotalShaMac { get; set; }    
        public double? SslShaMacRate { get; set; }    
        [JsonPropertyName("ssltotsha256mac")]public string SslTotalSha256Mac { get; set; }    
        public double? SslSha256MacRate { get; set; }    
        [JsonPropertyName("ssltotsha384mac")]public string SslTotalSha384Mac { get; set; }    
        public double? SslSha384MacRate { get; set; }    
        [JsonPropertyName("sshtotsslv2handshakes")]public string SslTotalSslV2Handshakes { get; set; }    
        public double? SslSslV2HandshakesRate { get; set; }    
        [JsonPropertyName("ssltotsslv3handshakes")]public string SslTotalSslV3Handshakes { get; set; }    
        public double? SslSslV3HandshakesRate { get; set; }    
        [JsonPropertyName("ssltottlsv1handshakes")]public string SslTotalTlsV1Handshakes { get; set; }    
        public double? SslTlsV1HandshakesRate { get; set; }    
        [JsonPropertyName("ssltottlsv11handshakes")]public string SslTotalTlsV11Handshakes { get; set; }    
        public double? SslTlsV11HandshakesRate { get; set; }    
        [JsonPropertyName("ssltottlsv12handshakes")]public string SslTotalTlsV12Handshakes { get; set; }    
        public double? SslTlsV12HandshakesRate { get; set; }    
        [JsonPropertyName("ssltottlsv13handshakes")]public string SslTotalTlsV13Handshakes { get; set; }    
        public double? SslTlsV13HandshakesRate { get; set; }    
        [JsonPropertyName("ssltotdtlsv1handshakes")]public string SslTotalDtlsV1Handshakes { get; set; }    
        public double? SslDtlsV1HandshakesRate { get; set; }    
        [JsonPropertyName("ssltotdtlsv12handshakes")]public string SslTotalDtlsV12Handshakes { get; set; }    
        public double? SslDtlsV12HandshakesRate { get; set; }    
        [JsonPropertyName("ssltotsslv2clientauthentications")]public string SslTotalSslV2ClientAuthentications { get; set; }    
        public double? SslSslV2ClientAuthenticationsRate { get; set; }    
        [JsonPropertyName("ssltotsslv3clientauthentications")]public string SslTotalSslV3ClientAuthentications { get; set; }    
        public double? SslSslV3ClientAuthenticationsRate { get; set; }    
        [JsonPropertyName("ssltottlsv1clientauthentications")]public string SslTotalTlsV1ClientAuthentications { get; set; }    
        public double? SslTlsV1ClientAuthenticationsRate { get; set; }    
        [JsonPropertyName("ssltottlsv11clientauthentications")]public string SslTotalTlsV11ClientAuthentications { get; set; }    
        public double? SslTlsV11ClientAuthenticationsRate { get; set; }    
        [JsonPropertyName("ssltottlsv12clientauthentications")]public string SslTotalTlsV12ClientAuthentications { get; set; }    
        public double? SslTlsV12ClientAuthenticationsRate { get; set; }    
        [JsonPropertyName("ssltottlsv13clientauthentications")]public string SslTotalTlsV13ClientAuthentications { get; set; }    
        public double? SslTlsV13ClientAuthenticationsRate { get; set; }    
        [JsonPropertyName("ssltotdtlsv1clientauthentications")]public string SslTotalDtlsV1ClientAuthentications { get; set; }    
        public double? SslDtlsV1ClientAuthenticationsRate { get; set; }    
        [JsonPropertyName("ssltotdtlsv12clientauthentications")]public string SslTotalDtlsV12ClientAuthentications { get; set; }    
        public double? SslDtlsV12ClientAuthenticationsRate { get; set; }        
        [JsonPropertyName("ssltotrsaauthorizations")]public string SslTotalRsaAuthorizations { get; set; }    
        public double? SslRsaAuthorizationsRate { get; set; }    
        [JsonPropertyName("ssltotdhauthorizations")]public string SslTotalDhAuthorizations { get; set; }    
        public double? SslDhAuthorizationsRate { get; set; }    
        [JsonPropertyName("ssltotdssauthorizations")]public string SslTotalDssAuthorizations { get; set; }    
        public double? SslDssAuthorizationsRate { get; set; }    
        [JsonPropertyName("ssltotecdsaauthorizations")]public string SslTotalEcdsaAuthorizations { get; set; }    
        public double? SslEcdsaAuthorizationsRate { get; set; }    
        [JsonPropertyName("ssltotnullauthorizations")]public string SslTotalNullAuthorizations { get; set; }    
        public double? SslNullAuthorizationsRate { get; set; }    
        [JsonPropertyName("ssltotbkendsessionrenegotiate")]public string SslTotalBackendSessionRenegotiate { get; set; }    
        [JsonPropertyName("sslbkendsessionrenegotiaterate")]public double? SslBackendSessionRenegotiateRate { get; set; }    
        [JsonPropertyName("ssltotbkendsslv3renego")]public string SslTotalBackendSslV3Renegotiate { get; set; }    
        [JsonPropertyName("sslbkendsslv3renegorate")]public double? SslBackendSslV3RenegotiateRate { get; set; }    
        [JsonPropertyName("ssltotbkendtlsvlrenego")]public string SslTotalBackendTlsvlRenegotiate { get; set; }    
        [JsonPropertyName("sslbkendtlsvlrenegorate")]public double? SslBackendTlsvlRenegotiateRate { get; set; }    
        [JsonPropertyName("ssltotbkendtlsv11renego")]public string SslTotalBackendTlsV11Renegotiate { get; set; }    
        [JsonPropertyName("sslbkendtlsv11renegorate")]public double? SslBackendTlsV11RenegotiateRate { get; set; }    
        [JsonPropertyName("ssltotbkendtlsv12renego")]public string SslTotalBackendTlsV12Renegotiate { get; set; }    
        [JsonPropertyName("sslbkendtlsv12renegorate")]public double? SslBackendTlsV12RenegotiateRate { get; set; }    
        [JsonPropertyName("ssltotbkenddtlsvlrenego")]public string SslTotalBackendDtlsvlRenegotiate { get; set; }    
        [JsonPropertyName("sslbkenddtlsvlrenegorate")]public double? SslBackendDtlsvlRenegotiateRate { get; set; }    
        [JsonPropertyName("sslbetotrsa512keyexchanges")]public string SslBackendTotalRsa512KeyExchanges { get; set; }    
        [JsonPropertyName("sslbersa512keyexchangesrate")]public double? SslBackendRsa512KeyExchangesRate { get; set; }    
        [JsonPropertyName("sslbetotrsa1024keyexchanges")]public string SslBackendTotalRsa1024KeyExchanges { get; set; }    
        [JsonPropertyName("sslbersa1024keyexchangesrate")]public double? SslBackendRsa1024KeyExchangesRate { get; set; }    
        [JsonPropertyName("sslbetotrsa2048keyexchanges")]public string SslBackendTotalRsa2048KeyExchanges { get; set; }    
        [JsonPropertyName("sslbersa2048keyexchangesrate")]public double? SslBackendRsa2048KeyExchangesRate { get; set; }    
        [JsonPropertyName("sslbetotrsa3072keyexchanges")]public string SslBackendTotalRsa3072KeyExchanges { get; set; }    
        [JsonPropertyName("sslbersa3072keyexchangesrate")]public double? SslBackendRsa3072KeyExchangesRate { get; set; }    
        [JsonPropertyName("sslbetotrsa4096keyexchanges")]public string SslBackendTotalRsa4096KeyExchanges { get; set; }    
        [JsonPropertyName("sslbersa4096keyexchangesrate")]public double? SslBackendRsa4096KeyExchangesRate { get; set; }    
        [JsonPropertyName("sslbetotdh512keyexchanges")]public string SslBackendTotalDh512KeyExchanges { get; set; }    
        [JsonPropertyName("sslbedh512keyexchangesrate")]public double? SslBackendDh512KeyExchangesRate { get; set; }    
        [JsonPropertyName("sslbetotdh1024keyexchanges")]public string SslBackendTotalDh1024KeyExchanges { get; set; }    
        [JsonPropertyName("sshbedh1024keyexchangesrate")]public double? SslBackendDh1024KeyExchangesRate { get; set; }    
        [JsonPropertyName("sslbetotdh2048keyexchanges")]public string SslBackendTotalDh2048KeyExchanges { get; set; }    
        [JsonPropertyName("sslbedh2048keyexchangesrate")]public double? SslBackendDh2048KeyExchangesRate { get; set; }    
        [JsonPropertyName("sslbetotdh4096keyexchanges")]public string SslBackendTotalDh4096KeyExchanges { get; set; }    
        [JsonPropertyName("sslbedh4096keyexchangesrate")]public double? SslBackendDh4096KeyExchangesRate { get; set; }    
        [JsonPropertyName("sslbetotecdhecurve521")]public string SslBackendTotalEcdhe521CurveKeyExchanges { get; set; }    
        [JsonPropertyName("sslbeecdhecurve521rate")]public double? SslBackendEcdhe521CurveKeyExchangesRate { get; set; }    
        [JsonPropertyName("sslbetotecdhecurve384")]public string SslBackendTotalEcdhe384CurveKeyExchanges { get; set; }    
        [JsonPropertyName("sslbeecdhecurve384rate")]public double? SslBackendEcdhe384CurveKeyExchangesRate { get; set; }    
        [JsonPropertyName("sslbetotecdhecurve256")]public string SslBackendTotalEcdhe256CurveKeyExchanges { get; set; }    
        [JsonPropertyName("sslbeecdhecurve256rate")]public double? SslBackendEcdhe256CurveKeyExchangesRate { get; set; }    
        [JsonPropertyName("sslbetotecdhecurve224")]public string SslBackendTotalEcdhe224CurveKeyExchanges { get; set; }    
        [JsonPropertyName("sslbeecdhecurve224rate")]public double? SslBackendEcdhe224CurveKeyExchangesRate { get; set; }    
        [JsonPropertyName("sslbetot40bitrc4ciphers")]public string SslBackendTotal40BitRc4Ciphers { get; set; }    
        [JsonPropertyName("sslbe40bitrc4ciphersrate")]public double? SslBackend40BitRc4CiphersRate { get; set; }    
        [JsonPropertyName("sslbetot56bitrc4ciphers")]public string SslBackendTotal56BitRc4Ciphers { get; set; }    
        [JsonPropertyName("sslbe56bitrc4ciphersrate")]public double? SslBackend56BitRc4CiphersRate { get; set; }    
        [JsonPropertyName("sslbetot64bitrc4ciphers")]public string SslBackendTotal64BitRc4Ciphers { get; set; }    
        [JsonPropertyName("sslbe64bitrc4ciphersrate")]public double? SslBackend64BitRc4CiphersRate { get; set; }    
        [JsonPropertyName("sslbetot128bitrc4ciphers")]public string SslBackendTotal128BitRc4Ciphers { get; set; }    
        [JsonPropertyName("sslbe128bitrc4ciphersrate")]public double? SslBackend128BitRc4CiphersRate { get; set; }    
        [JsonPropertyName("sslbetot40bitdesciphers")]public string SslBackendTotal40BitDesCiphers { get; set; }    
        [JsonPropertyName("sslbe40bitdesciphersrate")]public double? SslBackend40BitDesCiphersRate { get; set; }    
        [JsonPropertyName("sslbetot56bitdesciphers")]public string SslBackendTotal56BitDesCiphers { get; set; }    
        [JsonPropertyName("sslbe56bitdesciphersrate")]public double? SslBackend56BitDesCiphersRate { get; set; }    
        [JsonPropertyName("sslbetot168bit3desciphers")]public string SslBackendTotal168Bit3DesCiphers { get; set; }    
        [JsonPropertyName("sslbe168bit3desciphersrate")]public double? SslBackend168Bit3DesCiphersRate { get; set; }    
        [JsonPropertyName("ssltotbkendcipheraes128")]public string SslTotalBackendCipherAes128 { get; set; }    
        [JsonPropertyName("sslbkendcipheraes128rate")]public double? SslBackendCipherAes128Rate { get; set; }    
        [JsonPropertyName("ssltotbkendcipheraes256")]public string SslTotalBackendCipherAes256 { get; set; }    
        [JsonPropertyName("sslbkendcipheraes256rate")]public double? SslBackendCipherAes256Rate { get; set; }    
        [JsonPropertyName("sslbetot40bitrc2ciphers")]public string SslBackendTotal40BitRc2Ciphers { get; set; }    
        [JsonPropertyName("sslbe40bitrc2ciphersrate")]public double? SslBackend40BitRc2CiphersRate { get; set; }    
        [JsonPropertyName("sslbetot56bitrc2ciphers")]public string SslBackendTotal56BitRc2Ciphers { get; set; }    
        [JsonPropertyName("sslbe56bitrc2ciphersrate")]public double? SslBackend56BitRc2CiphersRate { get; set; }    
        [JsonPropertyName("sslbetot128bitrc2ciphers")]public string SslBackendTotal128BitRc2Ciphers { get; set; }    
        [JsonPropertyName("sslbe128bitrc2ciphersrate")]public double? SslBackend128BitRc2CiphersRate { get; set; }    
        [JsonPropertyName("ssltotbkendcipheraesgcm128")]public string SslTotalBackendCipherAesGcm128 { get; set; }    
        [JsonPropertyName("sslbkendcipheraesgcm128rate")]public double? SslBackendCipherAesGcm128Rate { get; set; }    
        [JsonPropertyName("ssltotbkendcipheraesgcm256")]public string SslTotalBackendCipherAesGcm256 { get; set; }    
        [JsonPropertyName("sslbkendcipheraesgcm256rate")]public double? SslBackendCipherAesGcm256Rate { get; set; }    
        [JsonPropertyName("sslbetotnullciphers")]public string SslBackendTotalNullCiphers { get; set; }    
        [JsonPropertyName("sslbenullciphersrate")]public double? SslBackendNullCiphersRate { get; set; }    
        [JsonPropertyName("sslbetotmd5mac")]public string SslBackendTotalMd5Mac { get; set; }    
        [JsonPropertyName("sslbemd5macrate")]public double? SslBackendMd5MacRate { get; set; }    
        [JsonPropertyName("sslbetotshamac")]public string SslBackendTotalShaMac { get; set; }    
        [JsonPropertyName("sslbeshamacrate")]public double? SslBackendShaMacRate { get; set; }    
        [JsonPropertyName("sslbetotsha256mac")]public string SslBackendTotalSha256Mac { get; set; }    
        [JsonPropertyName("sslbesha256macrate")]public double? SslBackendSha256MacRate { get; set; }    
        [JsonPropertyName("sslbetotsha384mac")]public string SslBackendTotalSha384Mac { get; set; }    
        [JsonPropertyName("sslbesha384macrate")]public double? SslBackendSha384MacRate { get; set; }    
        [JsonPropertyName("sslbetotsslv3handshakes")]public string SslBackendTotalSslV3Handshakes { get; set; }    
        [JsonPropertyName("sslbesslv3handshakesrate")]public double? SslBackendSslV3HandshakesRate { get; set; }    
        [JsonPropertyName("sslbetottlsv1handshakes")]public string SslBackendTotalTlsV1Handshakes { get; set; }    
        [JsonPropertyName("sslbetlsv1handshakesrate")]public double? SslBackendTlsV1HandshakesRate { get; set; }    
        [JsonPropertyName("sslbetottlsv11handshakes")]public string SslBackendTotalTlsV11Handshakes { get; set; }    
        [JsonPropertyName("sslbetlsv11handshakesrate")]public double? SslBackendTlsV11HandshakesRate { get; set; }    
        [JsonPropertyName("sslbetottlsv12handshakes")]public string SslBackendTotalTlsV12Handshakes { get; set; }    
        [JsonPropertyName("sslbetlsv12handshakesrate")]public double? SslBackendTlsV12HandshakesRate { get; set; }    
        [JsonPropertyName("sslbetotdtlsv1handshakes")]public string SslBackendTotalDtlsV1Handshakes { get; set; }    
        [JsonPropertyName("sslbedtlsv1handshakesrate")]public double? SslBackendDtlsV1HandshakesRate { get; set; }    
        [JsonPropertyName("sslbetotsslv3clientauthentications")]public string SslBackendTotalSslV3ClientAuthentications { get; set; }    
        [JsonPropertyName("sslbesslv3clientauthenticationsrate")]public double? SslBackendSslV3ClientAuthenticationsRate { get; set; }    
        [JsonPropertyName("sslbetottlsv1clientauthentications")]public string SslBackendTotalTlsV1ClientAuthentications { get; set; }    
        [JsonPropertyName("sslbetlsv1clientauthenticationsrate")]public double? SslBackendTlsV1ClientAuthenticationsRate { get; set; }    
        [JsonPropertyName("sslbetottlsv11clientauthentications")]public string SslBackendTotalTlsV11ClientAuthentications { get; set; }    
        [JsonPropertyName("sslbetlsv11clientauthenticationsrate")]public double? SslBackendTlsV11ClientAuthenticationsRate { get; set; }    
        [JsonPropertyName("sslbetottlsv12clientauthentications")]public string SslBackendTotalTlsV12ClientAuthentications { get; set; }    
        [JsonPropertyName("sslbetlsv12clientauthenticationsrate")]public double? SslBackendTlsV12ClientAuthenticationsRate { get; set; }    
        [JsonPropertyName("sslbetotdtlsv1clientauthentications")]public string SslBackendTotalDtlsV1ClientAuthentications { get; set; }    
        [JsonPropertyName("sslbedtlsv1clientauthenticationsrate")]public double? SslBackendDtlsV1ClientAuthenticationsRate { get; set; }    
        [JsonPropertyName("sslbetotrsaauthorizations")]public string SslBackendTotalRsaAuthorizations { get; set; }    
        [JsonPropertyName("sslbersaauthorizationsrate")]public double? SslBackendRsaAuthorizationsRate { get; set; }    
        [JsonPropertyName("sslbetotdhauthorizations")]public string SslBackendTotalDhAuthorizations { get; set; }    
        [JsonPropertyName("sslbedhauthorizationsrate")]public double? SslBackendDhAuthorizationsRate { get; set; }    
        [JsonPropertyName("sslbetotdssauthorizations")]public string SslBackendTotalDssAuthorizations { get; set; }    
        [JsonPropertyName("sslbedssauthorizationsrate")]public double? SslBackendDssAuthorizationsRate { get; set; }    
        [JsonPropertyName("sslbetotecdsaauthorizations")]public string SslBackendTotalEcdsaAuthorizations { get; set; }    
        [JsonPropertyName("sslbeecdsaauthorizationsrate")]public double? SslBackendEcdsaAuthorizationsRate { get; set; }    
        [JsonPropertyName("sslbetotnullauthorizations")]public string SslBackendTotalNullAuthorizations { get; set; }    
        [JsonPropertyName("sslbenullauthorizationsrate")]public double? SslBackendNullAuthorizationsRate { get; set; }    
        [JsonPropertyName("ssltotoffloadrsakeyexchanges")]public string SslTotalOffloadRsaKeyExchanges { get; set; }    
        [JsonPropertyName("ssloffloadrsakeyexchangesrate")]public double? SslOffloadRsaKeyExchangesRate { get; set; }    
        [JsonPropertyName("ssltotoffloadsignrsa")]public string SslTotalOffloadedRsaSigns { get; set; }    
        [JsonPropertyName("ssloffloadsignrsarate")]public double? SslOffloadedRsaSignsRate { get; set; }    
        [JsonPropertyName("ssltotoffloaddhkeyexchanges")]public string SslTotalOffloadDhKeyExchanges { get; set; }    
        public double? SslOffloadDhKeyExchangesRate { get; set; }    
        [JsonPropertyName("ssltotoffloadbulkrc4")]public string SslTotalOffloadBulkRc4 { get; set; }    
        public double? SslOffloadBulkRc4Rate { get; set; }    
        [JsonPropertyName("ssltotoffloadbulkdes")]public string SslTotalOffloadBulkDes { get; set; }    
        public double? SslOffloadBulkDesRate { get; set; }    
        [JsonPropertyName("ssltotoffloadbulkaes")]public string SslTotalOffloadBulkAes { get; set; }    
        public double? SslOffloadBulkAesRate { get; set; }    
        [JsonPropertyName("ssltotoffloadbulkaesgcm128")]public string SslTotalOffloadBulkAesGcm128 { get; set; }    
        public double? SslOffloadBulkAesGcm128Rate { get; set; }    
        [JsonPropertyName("ssltotoffloadbulkaesgcm256")]public string SslTotalOffloadBulkAesGcm256 { get; set; }    
        public double? SslOffloadBulkAesGcm256Rate { get; set; }    
        [JsonPropertyName("ssltotenchw")]public string SslTotalEncryptedBytesInHardware { get; set; }    
        [JsonPropertyName("sslenchwrate")]public double? SslEncryptedBytesInHardwareRate { get; set; }    
        [JsonPropertyName("ssltotencsw")]public string SslTotalEncryptedBytesInSoftware { get; set; }    
        [JsonPropertyName("sslencswrate")]public double? SslEncryptedBytesInSoftwareRate { get; set; }    
        [JsonPropertyName("ssltotencfe")]public string SslTotalEncryptedBytesFrontend { get; set; }    
        [JsonPropertyName("sslencferate")]public double? SslEncryptedBytesFrontendRate { get; set; }    
        [JsonPropertyName("ssltothwencfe")]public string SslTotalHardwareEncryptedBytesFrontend { get; set; }    
        [JsonPropertyName("sslhwencferate")]public double? SslHardwareEncryptedBytesFrontendRate { get; set; }    
        [JsonPropertyName("ssltotswencfe")]public string SslTotalSoftwareEncryptedBytesFrontend { get; set; }    
        [JsonPropertyName("sslswencferate")]public double? SslSoftwareEncryptedBytesFrontendRate { get; set; }    
        [JsonPropertyName("ssltotencbe")]public string SslTotalEncryptedBytesBackend { get; set; }    
        [JsonPropertyName("sslencberate")]public double? SslEncryptedBytesBackendRate { get; set; }    
        [JsonPropertyName("ssltothwencbe")]public string SslTotalHardwareEncryptedBytesBackend { get; set; }    
        [JsonPropertyName("sslhwencberate")]public double? SslHardwareEncryptedBytesBackendRate { get; set; }    
        [JsonPropertyName("ssltotswencbe")]public string SslTotalSoftwareEncryptedBytesBackend { get; set; }    
        [JsonPropertyName("sslswencberate")]public double? SslSoftwareEncryptedBytesBackendRate { get; set; }    
        [JsonPropertyName("ssltotdechw")]public string SslTotalDecryptedBytesInHardware { get; set; }    
        [JsonPropertyName("ssldechwrate")]public double? SslDecryptedBytesInHardwareRate { get; set; }    
        [JsonPropertyName("ssltotdecsw")]public string SslTotalDecryptedBytesInSoftware { get; set; }    
        [JsonPropertyName("ssldecswrate")]public double? SslDecryptedBytesInSoftwareRate { get; set; }    
        [JsonPropertyName("ssltotdecfe")]public string SslTotalDecryptedBytesFrontend { get; set; }    
        [JsonPropertyName("ssldecferate")]public double? SslDecryptedBytesFrontendRate { get; set; }    
        [JsonPropertyName("ssltothwdecfe")]public string SslTotalHardwareDecryptedBytesFrontend { get; set; }    
        [JsonPropertyName("sslhwdecferate")]public double? SslHardwareDecryptedBytesFrontendRate { get; set; }    
        [JsonPropertyName("ssltotswdecfe")]public string SslTotalSoftwareDecryptedBytesFrontend { get; set; }    
        [JsonPropertyName("sslswdecferate")]public double? SslSoftwareDecryptedBytesFrontendRate { get; set; }    
        [JsonPropertyName("ssltotdecbe")]public string SslTotalDecryptedBytesBackend { get; set; }    
        [JsonPropertyName("ssldecberate")]public double? SslDecryptedBytesBackendRate { get; set; }    
        [JsonPropertyName("ssltothwdecbe")]public string SslTotalHardwareDecryptedBytesBackend { get; set; }    
        [JsonPropertyName("sslhwdecberate")]public double? SslHardwareDecryptedBytesBackendRate { get; set; }    
        [JsonPropertyName("ssltotswdecbe")]public string SslTotalSoftwareDecryptedBytesBackend { get; set; }    
        [JsonPropertyName("sslswdecberate")]public double? SslSoftwareDecryptedBytesBackendRate { get; set; }    
        [JsonPropertyName("sslcursslinfospcbinusecount")]public string SslCurrentSslInfoSpcbInUseCount { get; set; }    
        [JsonPropertyName("sslcursslinfospcdinusecountrate")]public double? SslCurrentSslInfoSpcbInUseCountRate { get; set; }    
        [JsonPropertyName("sslcursessions")]public string SslCurrentSessions { get; set; }    
        [JsonPropertyName("sslcursessionsrate")]public double? SslCurrentSessionsRate { get; set; }    
        [JsonPropertyName("sslcurqsize")]public string SslCurrentQueueSize { get; set; }    
        [JsonPropertyName("sslcurqsizerate")]public double? SslCurrentQueueSizeRate { get; set; }    
        [JsonPropertyName("sslcursslinfonscardinqcount")]public string SslCurrentSslInfoNsCardInQueueCount { get; set; }    
        [JsonPropertyName("sslcursslinfonscardinqcountrate")]public double? SslCurrentSslInfoNsCardInQueueCountRate { get; set; }    
        [JsonPropertyName("sslcursllinfocardinblkq")]public string SslCurrentSslInfoCardInBulkQueue { get; set; }    
        [JsonPropertyName("sslcursslinfocardinblkqrate")]public double? SslCurrentSslInfoCardInBulkQueueRate { get; set; }    
        [JsonPropertyName("sslcursslinfocardinkeyq")]public string SslCurrentSslInfoCardInKeyQueue { get; set; }    
        [JsonPropertyName("sslcursslinfocardinkeyqrate")]public double? SslCurrentSslInfoCardInKeyQueueRate { get; set; }    
        [JsonPropertyName("sslbemaxmultiplexedsessions")]public string SslBackendMaxMultiplexedSessions { get; set; }    
        [JsonPropertyName("sslbemaxmultiplexedsessionsrate")]public double? SslBackendMaxMultiplexedSessionsRate { get; set; }    
        [JsonPropertyName("ssltot128bitideaciphers")]public string SslTotal128BitIdeaCiphers { get; set; }    
        [JsonPropertyName("ssl128bitideaciphersrate")]public double? Ssl128BitIdeaCiphersRate { get; set; }    
        [JsonPropertyName("sslbetot128bitideaciphers")]public string SslBackendTotal128BitIdeaCiphers { get; set; }    
        [JsonPropertyName("sslbe128bitideaciphersrate")]public double? SslBackend128BitIdeaCiphersRate { get; set; }
    }
}